# -*- coding: utf-8 -*-
"""
Part 1 Translations Dictionary - Batch 3 (Lines 8251 - 8400)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P1_DICT_3 = {
    8251: "[舜]「Đúng thế đấy, ngoan ngoãn nghe lời anh nhé」[p]",
    8252: "Tsubomi「Vâng ạ... anh [舜]... làm em sướng đi mà...」[p]",
    8253: "[playse storage=\"tubomi/voice_j1_2_tubomi_kaisi2.mp3\" buf=\"2\"]Tsubomi「Hôm nay... hãy cùng làm thật nhiều chuyện ngọt ngào nhé♡ Em đã chuẩn bị sẵn sàng hết rồi mà♡」[p]",
    8254: "[playse storage=\"tubomi/voice_j1_2_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Hà... hà...♡ Nó đang từ từ tiến vào trong kìa... To quá... Căng tức cả người em rồi...♡」[p]",
    8255: "[playse storage=\"tubomi/voice_j1_2_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「N-Nếu vào tới tận sâu nhất... chắc bụng em sẽ bị nghiền nát mất thôi...♡」[p]",
    8256: "[舜]「Không sao đâu mà. Nào, thả lỏng người ra... anh sẽ từ từ đút vào. Ưm, hà, a, a...」[p]",
    8257: "[playse storage=\"tubomi/voice_j1_2_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「A... a... a...♡ Trơn tuột... lọt vào trong rồi kìa♡ To lớn quá... bên trong bị nong căng hết cả ra rồi♡」[p]",
    8258: "[舜]「A, hẹp quá... Bên trong khít rịt thế này... Chắc phải từ từ làm cho quen dần mới được...」[p]",
    8259: "Tsubomi「A... a...♡ Nó nở to căng phồng lên rồi kìa♡ Hà, ưm... Muốn bắn ra nên đang rạo rực lắm rồi đúng không♡」[p]",
    8260: "Tsubomi「Đừng có nhịn mà hãy bắn ra đi... Em muốn anh trút hết toàn bộ vào em cơ♡ Cho em hết đi mà♡ Bạn gái của anh là em cơ mà đúng không?」[p]",
    8261: "[舜]「Đúng thế...! Anh chỉ muốn Tsubomi thôi...! Hà, hà, ưm! Em muốn anh bắn vào đâu?」[p]",
    8262: "Tsubomi「Hãy bắn lên khắp người em đi...♡ Hãy lưu lại mùi hương của anh [舜] trên người em đi...♡」[p]",
    8263: "[舜]「Phù, phù... Anh biết rồi! A, sắp ra rồi... Ra đây, ra ra ra! A, a... a...!」[p]",
    8264: "Tsubomi「Hức... a... a...♡ A... a...♡ Ôi... Tinh trùng bắn ngập tràn lên người em rồi...♡ Trắng xóa hết cả người rồi nè♡」[p]",
    8265: "[舜]「A... a... Phải chứng minh cho mọi người thấy Tsubomi là người của ai mới được chứ...!」[p]",
    8266: "Tsubomi「Ưm...♡ Không cần làm thế thì em cũng đã là người của anh từ lâu rồi mà♡」[p]",
    8267: "Tsubomi「Ư... ưm...♡ Ôi...♡ Ôi trời ơi♡ Bắn nhiều quá chừng... Thân thể em dính đầy tinh dịch nhầy nhụa hết cả rồi...♡」[p]",
    8268: "Tsubomi「Lượng tinh dịch nhiều thế này, nếu bắn vào bên trong... chắc chỉ một lần thôi là có em bé luôn rồi quá...♡」[p]",
    8269: "Tsubomi「Anh có ý định làm em mang bầu thật đấy à? Trời ạ... Vừa mới làm xong mà chỗ đó lại râm ran ngứa ngáy nữa rồi này」[p]",
    8270: "Tsubomi「Hức...♡ Phù, hà, a...♡ Hết chịu nổi rồi...♡ Ưm...♡ Em ra... Em lên đỉnh mất thôi♡」[p]",
    8271: "[舜]「Anh cũng sắp bắn rồi...! Anh muốn rót toàn bộ vào bên trong...! Nếu Tsubomi không thích thì anh dừng lại nhé」[p]",
    8272: "Tsubomi「Làm sao mà không thích được chứ♡ Cho em hết đi mà...♡ Hãy rót thật nhiều đến mức bên trong anh cạn sạch luôn đi♡ Mau lên anh...♡」[p]",
    8273: "[舜]「Từ bao giờ mà em lại biết làm nũng dâm đãng thế này hả...! Bắn đây...! Ra rồi, ra ra ra! Khốn thật!」[p]",
    8274: "Tsubomi「A... a...♡ Ưm...♡ Hức...♡ Bên trong... Bắn phì phì từng đợt... Đang trào ra bên trong em kìa♡」[p]",
    8275: "Tsubomi「A... a... a...♡ Bên trong ngập tràn tinh dịch rồi...♡ Hà, a, nếu chạm tới tận cổ tử cung thế này...♡」[p]",
    8276: "Tsubomi「Có khi sẽ mang bầu mất thôi♡ Nếu thế thì... Em chỉ còn cách trở thành vợ của anh thôi chứ còn gì nữa♡」[p]",
    8277: "Tsubomi「Ôi...♡ Ôi trời ơi...♡ Kh-Không chịu đâu...♡ Giọng điệu kỳ lạ cứ tự bật ra...♡ Mặt em cũng đê mê ngây dại hết cả rồi♡」[p]",
    8278: "[舜]「Vẻ mặt em dâm đãng không chịu nổi...! Bị bắn tinh vào trong... mà để lộ bộ mặt ngây dại thế này thì ai mà cưỡng lại được」[p]",
    8279: "Tsubomi「Đừng nhìn mà♡ Đừng nhìn bộ mặt xấu hổ này của em mà♡ Ôi, ôi trời ơi♡ Ưm, sướng quá đi mất♡」[p]",
    8280: "[playse storage=\"tubomi/voice_j_tubomi_kaisi3.mp3\" buf=\"2\"]Tsubomi「Một cô vợ nhỏ biết hầu hạ chuyện giường chiếu dâm đãng thế này thì sao nào? Đã vậy còn siêu cấp đáng yêu nữa chứ♡ Anh thích lắm đúng không?」[p]",
    8281: "[playse storage=\"tubomi/voice_j2_1_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Hà... hà... hà...♡ Đừng cử động nhé... Hôm nay để em tự làm hết cho...♡」[p]",
    8282: "[舜]「Không cần phải gượng ép đâu... Tsubomi, chờ chút đã. Hay để anh...」[p]",
    8283: "[playse storage=\"tubomi/voice_j2_1_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「Không được đâu...! Hãy nhìn chỗ nó đang đi vào đi này? Nào, hạ hông xuống... Em sẽ nuốt trọn con cu vào nhé?」[p]",
    8284: "[舜]「Tsubomi hôm nay... dâm quá thể đáng rồi đấy... A, chết tiệt... Cương cứng hết cỡ luôn rồi...」[p]",
    8285: "[playse storage=\"tubomi/voice_j2_1_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「Ưm...♡ A, a...♡ T-To quá... Đang chui vào rồi♡ Ưm...♡ Bên trong đầy ắp cả rồi này♡」[p]",
    8286: "[舜]「Hà, hà! A, chết rồi... Sắp ra mất! Tsubomi...!」[p]",
    8287: "Tsubomi「Hãy bắn hết lên người em đi♡ Em muốn người dính đầy tinh dịch nhơm nhớp cơ♡ Bắn thật nhiều đến mức trắng xóa cả người luôn đi anh♡」[p]",
    8288: "[舜]「Khốn thật! Dâm đãng quá mức rồi đấy... Mới mấy hôm trước chỉ cần nghe nói bậy bạ thôi là mặt đã đỏ bừng rồi cơ mà...」[p]",
    8289: "Tsubomi「Tại vì em đã bị anh biến thành người lớn mất rồi mà♡ Ưm...♡ A...♡ A...♡ Bắn lên đi, cho em tất cả đi mà♡」[p]",
    8290: "[舜]「Sao em lại dâm đến mức này cơ chứ...! Không xong rồi, ra mất...! Bắn đây! Khốn thật, a, a... a...!」[p]",
    8291: "Tsubomi「A...♡ A, a... a...♡ Tuyệt quá...♡ Vì hưng phấn quá nên anh bắn ra nhiều thế này sao?」[p]",
    8292: "[舜]「Vì Tsubomi quá đỗi gợi tình... nên anh không kìm nén nổi... Nhìn kìa, nó vẫn còn đang giật nảy lên này...」[p]",
    8293: "Tsubomi「Ưm... Nhờ vậy mà khắp người em dính đầy tinh dịch rồi nè...♡ Em bị nhuộm trọn mùi hương của anh [舜] mất rồi」[p]",
    8294: "Tsubomi「A... hức♡ Cái gì thế này... Trời ạ... Toàn thân em trơn tuột nhầy nhụa hết cả rồi nè...♡」[p]",
    8295: "Tsubomi「Thực sự là bị bắn lên trắng xóa cả người luôn rồi này♡ Đã vậy mùi còn nồng nặc nữa...♡ Thế này thì chết mất thôi♡」[p]",
    8296: "Tsubomi「Phù... Hà, chỉ cần ngửi mùi thôi... Là nơi sâu kín lại nhói lên sung sướng rồi này♡」[p]",
    8297: "Tsubomi「Ưm...♡ Tuyệt quá♡ Đầu khấc lại nở to lên rồi kìa♡ Hà, a...♡ Nó đang giật giật kìa... Sắp bắn nữa sao anh?」[p]",
    8298: "[舜]「Sắp ra rồi...! Rút ra nhanh đi em... Mau lên...! Anh sắp xuất tinh tới nơi rồi...!」[p]",
    8299: "Tsubomi「Không chịu đâu♡ Bắn vào bên trong đi anh♡ Hãy nhìn em... Vừa ý thức được rằng anh đang bắn vào bên trong em... Vừa rót hết toàn bộ vào đây đi♡」[p]",
    8300: "Tsubomi「Anh sẽ biến em... Thành người phụ nữ của anh cơ mà đúng không♡ Mau lên... Cho em đi anh♡」[p]",
}
