# -*- coding: utf-8 -*-
"""
Part 1 Translations Dictionary - Batch 1 (Lines 8021 - 8168: H_serihu_tubomi.ks)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P1_DICT = {
    8021: "Tsubomi「Anh [舜] cứ việc đưa hông theo ý thích đi ạ...♡ Em muốn anh khuấy đảo cô bé nhầy nhụa lên cơ♡」[p]",
    8022: "Tsubomi「A...♡ Hức...♡ Ưm...♡ Ôi...♡ Em chẳng còn nghĩ được gì nữa rồi♡ Trong đầu chỉ toàn thấy sướng thôi♡」[p]",
    8023: "[舜]「Mặt em dâm đãng hết cả ra rồi kìa. Có biết bây giờ trông vẻ mặt mình như thế nào không hả?」[p]",
    8024: "Tsubomi「Không chịu đâu♡ Ôi trời♡ Cô bé sướng quá rồi... l-làm sao giữ được vẻ mặt ngoan ngoãn đáng yêu nữa chứ♡」[p]",
    8025: "Tsubomi「Ôi... ôi trời ơi...♡ Hức...♡ Chỉ mới có ngón tay thôi mà... em sắp lên đỉnh rồi này...♡ Sướng quá đi mất♡」[p]",
    8026: "[舜]「Thế không cần đút cu vào em cũng thỏa mãn rồi à? Khỏi cần đút vào nữa nhé?」[p]",
    8027: "Tsubomi「Không chịu đâu, không chịu đâu mà♡ Đút con cu vào đi anh♡ Em muốn anh dập thụt liên tục vào cơ♡」[p]",
    8028: "Tsubomi「Ư... hức♡ Mông em, đừng mà, đừng làm nó lỏng ra... đừng ngoáy vào chỗ đó mà♡」[p]",
    8029: "[舜]「Phải dạy cho chỗ này nhớ rằng ngoài việc bài tiết ra thì còn có thể đút vào được nữa chứ...」[p]",
    8030: "Tsubomi「Á, không được đâu♡ Ôi...♡ Ôi trời ơi♡ Mông em... sẽ hỏng mất thôi♡ Không được đâu mà♡」[p]",
    8031: "Tsubomi「Ôi...♡ Ôi...♡ Đang được xoa nắn mềm ra này... á... ngón tay lọt vào mất rồi♡ Không được, không được đâu♡」[p]",
    8032: "[舜]「Hê~? Lúc tắm em còn kỳ cọ sạch sẽ chỗ mông cơ mà. Rõ ràng là đang mong đợi còn gì?」[p]",
    8033: "Tsubomi「A... hức♡ N-Nhưng mà... chỗ đó bẩn lắm... nên là...♡ Ôi...♡ Ôi trời ơi♡」[p]",
    8034: "Tsubomi「Ôi...♡ Ôi...♡ Đừng banh mông em ra mà♡ Bị nhào nặn thế này... nó sẽ nhão ra mất thôi♡」[p]",
    8035: "Tsubomi「Ngón tay không vào được đâu♡ Chỗ đó... vẫn còn khép chặt lắm... không làm được đâu ạ♡」[p]",
    8036: "Tsubomi「Thay vì mông... em muốn anh nuông chiều chăm sóc cho cô bé đang tan chảy ướt đẫm này cơ mà♡」[p]",
    8037: "Tsubomi「Ôi trời ơi♡ Ôi...♡ Bằng lỗ mông mà... em sắp ra, sắp lên đỉnh mất rồi♡ Ôi...♡ Ôi...♡ Ôi...♡」[p]",
    8038: "Tsubomi「Ư... hức♡ Lỗ mông cứ giật giật không ngừng được...♡ Sướng kinh khủng luôn ý♡」[p]",
    8039: "Tsubomi「A... ưm♡ Rõ ràng là lỗ mông... vậy mà cô bé phía trước cứ ngứa ngáy râm ran không dừng được♡ Chỗ nào cũng sướng hết á♡」[p]",
    8040: "Tsubomi「A...♡ A...♡ A...♡ Con cu hôm nay to hơn mọi khi nữa♡ Tận sâu bên trong như bị nghiền nát ra vậy♡」[p]",
    8041: "[舜]「Kinh thật, cái chỗ cưng cứng gồ lên này... bình thường đâu được chạm vào đâu nhỉ? Đây này!」[p]",
    8042: "Tsubomi「Ôi...♡ Hức... a...♡ Chỗ đó... tê rần rần lên rồi... tuyệt đối không được chạm vào đâu mà♡ Á...♡」[p]",
    8043: "Tsubomi「Ôi...♡ Ôi...♡ Cuối cùng cũng tới rồi♡ Em thèm cái này lắm rồi♡ Em muốn anh đâm thật nhiều vào đây cơ♡」[p]",
    8044: "[舜]「Bắt em nhịn nãy giờ nên bên trong nóng ran lên rồi kìa... ướt sũng nhầy nhụa luôn rồi này」[p]",
    8045: "Tsubomi「A... hức♡ Giống như đang nhấm nháp thưởng thức vậy... bị cọ sát bên trong sướng điên lên được♡ Thích quá đi...♡」[p]",
    8046: "Tsubomi「Hức...♡ A...♡ Ôi, ôi trời♡ Tận sâu trong bụng, như bị nghiến nát ra rồi♡ A... a...♡」[p]",
    8047: "Tsubomi「Vì anh mãi không chịu đút vào... nên em cứ bồn chồn thèm khát muốn có nó sớm thôi...♡」[p]",
    8048: "Tsubomi「Ưm...♡ Bù cho lúc nãy phải nhịn, hãy đâm thật nhiều vào đi...♡ Đút sâu tận đáy... làm em tơi bời đi anh♡」[p]",
    8049: "Tsubomi「A... a... a...♡ Chạm đúng chỗ nhạy cảm rồi♡ Nó đâm thụt vào... ôi...♡ Ôi trời ơi...♡」[p]",
    8050: "Tsubomi「Chỗ đó... chỗ đó yếu lắm mà♡ Anh cứ nhắm thẳng vào đó đâm liên tục thôi♡ Ôi trời♡ Ôi...♡ Ôi...♡」[p]",
    8051: "Tsubomi「A... a...♡ Sướng quá đi mất♡ Em ra mất thôi♡ Trong đầu như có pháo hoa nổ tung bép bép vậy á♡」[p]",
    8052: "Tsubomi「Ôi...♡ Ôi...♡ Ôi...♡ Mãnh liệt quá... tuyệt quá đi♡ Em hỏng mất♡ Em sẽ bị anh làm hỏng mất thôi♡」[p]",
    8053: "[舜]「Định trốn đi đâu hả? Đã thèm thuồng thế này thì phải ngoan ngoãn mà tiếp nhận cho hết, chứ hả!」[p]",
    8054: "Tsubomi「Hức... a...♡ Ôi...♡ Con cu to quá♡ Chạm tới tận sâu đáy bụng em luôn rồi♡」[p]",
    8055: "Tsubomi「Ư... ôi...♡ Phía bên trong, bị đẩy nhô cả lên rồi kìa♡ Bị con cu đội cả bụng lên rồi này♡」[p]",
    8056: "[舜]「Thật luôn kìa... À, mỗi lần thúc lên là bụng lại nhấp nhô phập phồng. Dâm thật sự」[p]",
    8057: "Tsubomi「Ôi...♡ Ôi trời...♡ Hỏng mất thôi♡ Bên trong bụng, con cu đang tung hoành dữ dội quá mà♡」[p]",
    8058: "Tsubomi「Ư...♡ Bị ép chặt vào trong rồi♡ A, kích thích mạnh quá, em không chịu nổi nữa đâu♡」[p]",
    8059: "Tsubomi「Ôi...♡ Đây là gieo giống sao anh? Hà...♡ Hà...♡ Cuộc ân ái chỉ để rót tinh trùng vào trong♡」[p]",
    8060: "Tsubomi「Tuyệt quá...♡ Em cảm nhận được con cu đang nở to dần bên trong...♡ Hà, a, kinh khủng thật đấy♡」[p]",
    8061: "Tsubomi「Hức... a...♡ Ôi...♡ Sướng quá đi♡ Hông em cứ tự động lắc lư dập dềnh theo mất rồi♡」[p]",
    8062: "[舜]「Khốn thật, ghê quá đi mất...! Nó bóp chặt kinh khủng...! A, chết tiệt, anh sắp bắn rồi...!」[p]",
    8063: "Tsubomi「Hà...♡ Hà...♡ Bắn nhanh đi anh♡ Rót đầy tinh trùng vào đi♡ Em muốn anh thụ tinh tạo em bé cho em cơ♡」[p]",
    8064: "[舜]「Với độ dâm đãng của Tsubomi bây giờ thì gạ gẫm ngon lành rồi nhỉ? Anh đã dạy bao nhiêu lần rồi. Nào, mau lên...」[p]",
    8065: "Tsubomi「Hà...♡ Hà, ưm...♡ Cô bé của Tsubomi... nóng rực ướt đẫm lắm rồi, hãy rót đầy tinh trùng của anh [舜] vào đi ạ...♡」[p]",
    8066: "Tsubomi「Cứ việc đưa hông theo ý thích, giữ chặt lấy cơ thể em... rồi bắn thật nhiều dòng tinh dịch nóng hổi mới ra vào đây nhé...♡」[p]",
    8067: "Tsubomi「Phù...♡ Phù...♡ Em muốn anh vừa cọ đầu khấc vào tận sâu đáy cô bé vừa xuất thật nhiều tinh trùng vào cơ♡」[p]",
    8068: "[舜]「Kinh thật, vừa nói vừa tự thấy nứng kìa... Mặt Tsubomi trông dâm đãng hết nấc luôn rồi đấy」[p]",
    8069: "Tsubomi「Tại vì... tưởng tượng cảnh bị đâm phầm phập phát ra tiếng tới tận đáy, cô bé của em lại ngứa ngáy râm ran lên mất rồi...♡」[p]",
    8070: "Tsubomi「Đã chuẩn bị sẵn sàng để đón nhận tinh trùng rồi này♡ Hưng phấn quá, có khi đến cả tử cung cũng sẵn sàng luôn rồi ý」[p]",
    8071: "Tsubomi「Nếu bây giờ rót vào... hạt giống em bé sẽ đâm xuyên tận đáy bụng, chạm vào trứng rồi thụ tinh mất thôi♡」[p]",
    8072: "Tsubomi「Em sẽ bị biến thành mẹ trẻ con mất thôi♡ Hà~♡ Hà~♡ Rõ ràng là không được... vậy mà lại dâm đãng thế này♡」[p]",
    8073: "Tsubomi「Chụt...♡ Chụt... mút... chụt chụt♡ Ưm, tự bản thân em lại chủ động hôn sâu quấn lưỡi thế này cơ chứ♡」[p]",
    8074: "Tsubomi「Em... đã biến thành cơ thể dâm đãng mất rồi♡ Hà, hà...♡ Nếu không được làm chuyện ân ái thì──」[p]",
    8075: "Tsubomi「Cô bé sẽ cứ ngứa ngáy râm ran... dù có tự thủ dâm cũng chẳng thể nào thỏa mãn nổi cơ thể này nữa rồi mà♡」[p]",
    8076: "[舜]「Chụt, mút, nào, em muốn được quấn lưỡi đúng không? Mở miệng ra thè lưỡi tới đây. Cho anh xem bộ mặt đê mê ngây dại của em đi」[p]",
    8077: "Tsubomi「Vâng ạ♡ A... hà♡ Chụt, mút, chụt chụt, rột rột...♡ Sướng quá đi anh ơi♡」[p]",
    8078: "Tsubomi「Mút, chụt, em thích hôn sâu lắm♡ A... phù♡ Rột rột rột. Em cảm ơn anh nhiều lắm ạ♡」[p]",
    8079: "Tsubomi「A...♡ Hôn sâu ướt át hơn nữa đi anh♡ Mút, nuốt, chụt chụt chụt♡」[p]",
    8080: "Tsubomi「Hà, a...♡ Em thích quấn lưỡi lắm cơ♡ Chụt mút chụt chụt♡ Chụt, mút mút...♡」[p]",
    8081: "Tsubomi「Chỉ hôn thôi... mà cô bé cứ nhấp nhổm ngứa ngáy liên tục...♡ Chụt chụt chụt. Sướng quá đi anh♡」[p]",
    8082: "Tsubomi「Mút, rột rột...♡ Mút, ưm...♡ A... a...♡ Sướng quá đi... em thích lắm♡」[p]",
    8083: "Tsubomi「Mút, chụt chụt mút♡ Ôi...♡ Ôi trời♡ Cảm giác như cả khoang miệng bị anh nuốt chửng vậy... tuyệt quá đi♡」[p]",
    8084: "Tsubomi「Ưm...♡ Cứ như đang quan hệ bằng miệng vậy á♡ Chụt chụt, mút, rột rột rột♡」[p]",
    8085: "[舜]「Vừa nãy em cũng tự bóp vú đấy thôi... nhưng phải tóm chặt lấy rồi nhào nặn thật mạnh bạo vào chứ...!」[p]",
    8086: "Tsubomi「A... a... a...♡ Em xin lỗi...♡ A...♡ Lần này, em sẽ nắm thật chắc lấy cặp vú mà bóp ạ♡」[p]",
    8087: "Tsubomi「Giống như đang được anh [舜] nặn vậy... em sẽ dồn hết sức nhào nặn cho hai bầu ngực méo mó biến dạng luôn ạ♡」[p]",
    8088: "Tsubomi「A...♡ Nhìn này... ngực em bắt đầu mềm nhũn ra rồi nè♡ Bị nhào nặn tơi bời, nó mềm mịn như bánh bông lan ý♡」[p]",
    8089: "Tsubomi「Bóp ngực sướng quá...♡ Hãy nhào nặn nhiều hơn nữa đi anh♡ Hãy làm cho nó mềm nhũn ra trong lòng bàn tay anh [舜] đi♡」[p]",
    8090: "Tsubomi「Vâng ạ♡ A...♡ A...♡ Em thích ngực lắm... hãy chạm vào nhiều hơn nữa đi... bóp chặt đến mức biến dạng luôn cũng được mà♡」[p]",
    8091: "[舜]「Bị bóp ngực nhiều thế này, lỡ hỏng mất dáng ngực thì sao hả? Có làm người mẫu được nữa không đấy?」[p]",
    8092: "Tsubomi「A... hức♡ Em sẽ... chăm sóc kỹ càng nên không sao đâu mà♡ Với lại em đâu phải người mẫu khỏa thân đâu chứ♡」[p]",
    8093: "Tsubomi「Em không muốn anh dừng lại đâu♡ Bị tóm chặt rồi dùng lực nhào nặn tơi bời thế này... em thích lắm cơ mà♡」[p]",
    8094: "Tsubomi「A... a... a...♡ Tuyệt quá đi♡ Em lên đỉnh bằng ngực mất thôi...♡ Sắp ra rồi...♡ Ôi, ôi trời ơi...♡」[p]",
    8095: "[舜]「Nhìn xem, đầu nhũ hoa cũng dựng đứng cứng ngắc lên rồi kìa... Dâm thật sự... Em cũng muốn được sờ vào đầu ti đúng không?」[p]",
    8096: "Tsubomi「Vâng ạ♡ A... em muốn anh chạm vào lắm♡ Hãy vân vê mơn trớn đầu nhũ hoa để nuông chiều em đi ạ♡」[p]",
    8097: "Tsubomi「Ôi...♡ Ôi...♡ Ôi...♡ Đầu ti bị vân vê kìa♡ Tuyệt quá♡ Ưm... ôi♡ Nó truyền kích thích xuống tận cô bé luôn này♡」[p]",
    8098: "[舜]「Dâm vãi... Lắc lư hông thế này mà không thấy bậy bạ hả? Định đi thử vai người mẫu với bộ dạng này đấy à?」[p]",
    8099: "Tsubomi「Ôi trời...♡ T-Tại vì... ngực sướng quá... cơ thể em cứ tự động di chuyển theo thôi mà♡」[p]",
    8100: "[舜]「Vừa bị vân vê đầu ti thế này, vừa coi như đang thử vai mà tự giới thiệu bản thân đi xem nào」[p]",
}
