# -*- coding: utf-8 -*-
"""
Part 1 Translations Dictionary - Batch 4 (Lines 8301 - 8420)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P1_DICT_4 = {
    8301: "Tsubomi「Anh [舜]... Mau lên... Đút vào bên trong đi mà♡」[p]",
    8302: "[舜]「Bắn nhé...! Anh bắn vào trong đây! Nhận lấy toàn bộ tinh dịch của anh đi!」[p]",
    8303: "Tsubomi「A... a... a...♡ Bên trong... Bắn ừng ực từng đợt rồi kìa♡ Sướng quá đi anh ơi♡」[p]",
    8304: "[舜]「Khốn thật... Trong này nóng ran như thiêu đốt vậy...! Phê quá đi mất!」[p]",
    8305: "Tsubomi「Hức... a...♡ Ôi...♡ Ôi trời ơi♡ Tuyệt quá... Trào ra ngoài rồi... Bắn ra nhiều kinh khủng luôn á♡」[p]",
    8306: "Tsubomi「Bị bắn nhiều đến mức này... Thì toàn bộ bên trong đầy ắp tinh dịch rồi còn gì nữa♡ Chắc chạm tới tận sâu đáy cùng luôn rồi quá♡」[p]",
    8307: "Tsubomi「Từ nãy tới giờ... Đầu khấc cứ cọ sát thẳng vào cửa tử cung cơ mà đúng không? Bị rót thẳng trực tiếp vào bên trong rồi...♡」[p]",
    8308: "[playse storage=\"tubomi/voice_j_tubomi_kaisi3.mp3\" buf=\"2\"]Tsubomi「Một cô vợ nhỏ biết hầu hạ chuyện giường chiếu dâm đãng thế này thì sao nào? Đã vậy còn siêu cấp đáng yêu nữa chứ♡ Anh thích lắm đúng không?」[p]",
    8309: "[playse storage=\"tubomi/voice_j2_2_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Con cu đang cương cứng cong vút lên rồi nè, em sẽ đút nó vào trong ngay đây...♡ Đừng cử động nhé? Cứ thế này, từ từ thôi──」[p]",
    8310: "[舜]「Khốn thật, lối vào nóng rực lên rồi... Ướt sũng nhầy nhụa luôn kìa」[p]",
    8311: "[playse storage=\"tubomi/voice_j2_2_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「Đúng thế đấy♡ Tại vì anh cứ chạm vào liên tục... Nên nó mới tan chảy ra thế này nè... Ưm, a...♡ Con cu to lớn đang chui vào trong rồi...」[p]",
    8312: "[playse storage=\"tubomi/voice_j2_2_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「Hức... a...♡ A...♡ A...♡ Tuyệt quá... Bên trong bị nong rộng hết cả ra rồi kìa♡ Ưm, ư... ưm♡」[p]",
    8313: "[舜]「A... a...! Không xong rồi... Sắp ra mất rồi... Tsubomi... Cho anh bắn tinh đi...!」[p]",
    8314: "Tsubomi「Vẫn chưa được đâu♡ Em muốn con cu cương cứng ngắc sắp bắn này... Đâm thụt thật nhiều vào tận sâu bên trong cơ♡」[p]",
    8315: "Tsubomi「Nhìn này...♡ Khốn thật, bên trong nó cứ giật giật thắt lại... Vì muốn bắn, muốn xuất tinh lắm rồi đúng không nào♡ Đáng yêu ghê♡」[p]",
    8316: "[舜]「H-Hết chịu nổi rồi...! A, ra mất... Bắn đây, bắn bắn bắn! Anh xuất đây...!」[p]",
    8317: "Tsubomi「Đành chịu vậy thôi nè♡ Bắn hết lên người em đi...♡ Để em bị nhuộm trọn trong tinh dịch của anh nào...♡」[p]",
    8318: "Tsubomi「Ư... hức♡ Ôi trời ơi♡ A...♡ Bù cho lúc nãy phải nhịn... Bắn ra nhiều kinh khủng khiếp luôn nè...♡」[p]",
    8319: "Tsubomi「A...♡ Thực sự là... Dính đầy tinh dịch khắp người rồi còn gì nữa♡ Toàn thân em nồng nặc mùi ân ái luôn rồi...」[p]",
    8320: "Tsubomi「Trời ạ... Rõ ràng cứ tưởng là xong rồi cơ chứ... Vậy mà cơ thể lại nóng ran lên nữa rồi...♡ Đừng có làm em nứng thêm nữa mà」[p]",
    8321: "Tsubomi「Hức... a...♡ Ôi...♡ Ôi trời ơi♡ A...♡ Hà, em bị anh đánh dấu chủ quyền mất rồi♡」[p]",
    8322: "Tsubomi「Thế này thì... Chỉ tắm sơ qua thôi làm sao mà hết mùi được chứ...♡ Phù... Phù phù♡ Mùi nồng thật đấy♡」[p]",
    8323: "Tsubomi「Mùi hương xộc thẳng vào tận sâu trong đầu...♡ Khiến em choáng váng cả người...♡ Ưm, hà... Sướng quá đi mất thôi♡」[p]",
    8324: "Tsubomi「Phù...♡ Phù...♡ Phù...♡ Anh muốn bắn vào bên trong em đúng không...? Muốn áp sát vào nơi sâu nhất... Rồi bắn phì phì từng đợt vào đúng không...♡」[p]",
    8325: "Tsubomi「Nếu muốn bắn dòng tinh trùng nóng hổi cô đặc tích tụ bấy lâu nay ra... Thì hãy nói câu 『Anh yêu em』 đàng hoàng đi đã nào♡」[p]",
    8326: "[舜]「Anh yêu em mà...! Với anh chỉ có Tsubomi thôi...! Hà, a... Ra mất... Nguy hiểm quá rồi!」[p]",
    8327: "Tsubomi「Ưm...♡ Em hạnh phúc lắm♡ Bắn ra đi anh♡ Cứ việc trút hết toàn bộ vào bên trong em đi ạ♡」[p]",
    8328: "Tsubomi「A... a... a...♡ B-Bên trong... Tinh dịch đang trào ừng ực vào trong em rồi...♡ Ôi...♡ Ôi trời ơi♡」[p]",
    8329: "[舜]「Con cu của anh, có khi đang dốc hết sức để biến Tsubomi thành người của riêng mình đấy...」[p]",
    8330: "Tsubomi「Ưm...♡ Không cần phải gồng mình đến thế đâu mà, em đã là người của anh từ lâu lắm rồi cơ mà♡」[p]",
    8331: "Tsubomi「Ư...♡ Ôi...♡ A... Hỏng mất thôi...♡ Bắn ra một lượng khổng lồ luôn rồi này♡」[p]",
    8332: "Tsubomi「Đây chính là... Minh chứng cho thấy anh yêu em nhiều đến nhường nào đúng không nè♡ Trào cả ra ngoài luôn rồi kìa♡」[p]",
    8333: "Tsubomi「Cứ nghĩ đến chuyện anh vừa nghĩ về em, vừa vì em mà hưng phấn đến mức này... Là em thấy vừa hạnh phúc vừa vui sướng vô cùng luôn ý♡」[p]",
    8334: "[playse storage=\"tubomi/voice_r_tubomi_kaisi1.mp3\" buf=\"2\"]Tsubomi「N-Này! Ở một nơi như thế này mà anh đang nghĩ cái quái gì thế hả! Đương nhiên là không được rồi...!」[p]",
    8335: "[playse storage=\"tubomi/voice_r1_1_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Đ-Đủ rồi đấy chứ... Làm chuyện này ở đây nữa là không được đâu... Buông em ra đi!」[p]",
    8336: "[舜]「Nhưng mà anh đã chuẩn bị sẵn sàng hết rồi... Tsubomi phía dưới cũng hé mở ướt át giật giật liên hồi rồi kìa」[p]",
    8337: "[playse storage=\"tubomi/voice_r1_1_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「A, không được, đừng có cọ vào mà... Nó sẽ chui lọt vào thật đấy♡ A, đừng mà... Đầu khấc chạm vào──」[p]",
    8338: "[playse storage=\"tubomi/voice_r1_1_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「Vào mất... A...♡ Nó chui vào mất rồi... A, ưm...♡ Không được, không được đâu mà♡ A... a... a...♡」[p]",
    8339: "[舜]「Ghê thật... Nó trơn tuột lọt hẳn vào trong rồi này... Khốn thật... Co bóp chặt kinh khủng...」[p]",
    8340: "[舜]「Phù... Phù... Phù... Nguy rồi, anh tới giới hạn rồi... Sắp ra mất... Em muốn anh bắn vào đâu nào!?」[p]",
    8341: "Tsubomi「Hả... Đ-Đâu cũng được hết á. Anh muốn bắn vào chỗ nào anh thích thì cứ bắn đi...」[p]",
    8342: "[舜]「Bắn lên người em được chứ? Anh sẽ nhuộm trắng toàn thân Tsubomi bằng tinh dịch của anh nhé...!」[p]",
    8343: "Tsubomi「Hà, a...♡ Đừng có cố tình tuyên bố to rõ ràng thế chứ♡ Càng làm cho... Chỗ đó của em ngứa ngáy thêm thôi... A, a...♡」[p]",
    8344: "[舜]「Ra đây... Hà, a, a... a...!」[p]",
    8345: "Tsubomi「Hức...♡ A... a...♡ Ấm áp quá...♡ Tinh dịch bắn lên người em rồi... Mùi nồng nặc luôn kìa♡」[p]",
    8346: "[舜]「Hà... Hà... Đó là mùi của giống đực đấy... Anh đã luôn muốn bôi khắp người Tsubomi rồi...」[p]",
    8347: "Tsubomi「Ý anh là muốn đánh dấu chủ quyền chứ gì? Cứ như động vật hoang dã vậy... Bị nhuộm trọn mùi hương của anh mất rồi♡」[p]",
    8348: "Tsubomi「A... a... a...♡ Trời ạ... Nhiều kinh khủng... Th-Thực sự là bị dính đầy tinh dịch khắp người rồi còn gì nữa♡」[p]",
    8349: "Tsubomi「Bắn ra nhiều quá rồi đấy... Anh đã nứng đến mức nào thế không biết...! Ưm... Khắp người trơn nhẫy hết cả rồi...」[p]",
    8350: "Tsubomi「Đã vậy... Mùi còn đặc quánh nữa chứ♡ Trời ạ... Tận đáy bụng... Lại nhói lên rạo rực rồi. Cơ thể em lại tự động phản ứng mất rồi nè」[p]",
    8351: "Tsubomi「A... a...♡ Mới vừa xong thôi mà... Đã muốn làm tiếp nữa rồi sao? Dâm đãng thật đấy」[p]",
    8352: "[舜]「Tại vì nhìn Tsubomi thế này gợi cảm quá... Không kìm lại được」[p]",
    8353: "Tsubomi「Hết cách với anh luôn... Lần này, hãy làm cho em thật sướng đấy nhé♡」[p]",
    8354: "Dẫn chuyện|Tôi giữ chặt lấy bờ mông tròn trịa của Tsubomi rồi bắt đầu đưa đẩy nhịp nhàng.[p]",
    8355: "Tsubomi「A... ưm... sâu quá... chạm tới tận đáy rồi...♡」[p]",
    8356: "[舜]「Bên trong em nóng và khít quá... Sướng không chịu nổi」[p]",
    8357: "Tsubomi「Em cũng thế... sướng đến phát điên lên rồi nè...♡」[p]",
    8358: "Dẫn chuyện|Tiếng da thịt va chạm bạch bạch vang vọng khắp căn phòng yên tĩnh.[p]",
    8359: "Tsubomi「A... a... nhanh quá... chậm lại một chút đi anh...♡」[p]",
    8360: "[舜]「Không dừng lại được đâu... Anh sắp bắn rồi!」[p]",
    8361: "Tsubomi「Bắn vào trong đi anh! Hãy lấp đầy em đi!」[p]",
    8362: "Dẫn chuyện|Tôi thúc một cú thật mạnh rồi xuất trọn dòng tinh dịch nóng hổi vào tận sâu bên trong.[p]",
    8363: "[playse storage=\"tubomi/voice_r1_2_tubomi_kaisi2.mp3\" buf=\"2\"]Tsubomi「Lại nữa sao...? Thật là, anh nghiện cơ thể của em rồi đúng không?」[p]",
    8364: "[playse storage=\"tubomi/voice_r1_2_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Hà... hà... Lần này em sẽ chủ động nhé...♡」[p]",
    8365: "[舜]「Để xem em làm thế nào nào」[p]",
    8366: "[playse storage=\"tubomi/voice_r1_2_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「Ưm... vào rồi nè... to quá đi...♡」[p]",
    8367: "[playse storage=\"tubomi/voice_r1_2_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「A... a... tự mình nhấp thế này sướng ghê á...♡」[p]",
    8368: "[舜]「Tsubomi giỏi thật đấy... Nhìn em từ góc này gợi cảm dã man」[p]",
    8369: "Tsubomi「Khen em nữa đi... Em muốn nghe anh khen nhiều hơn nữa cơ...♡」[p]",
    8370: "[舜]「Em là tuyệt nhất, Tsubomi à...」[p]",
    8371: "Tsubomi「Ưm... em yêu anh [舜] nhiều lắm...♡」[p]",
    8372: "Dẫn chuyện|Tsubomi vừa nói vừa nhấp hông liên tục, từng giọt mồ hôi lăn dài trên làn da trắng mịn.[p]",
    8373: "Tsubomi「A... a... sắp lên đỉnh rồi... em sắp ra mất thôi...♡」[p]",
    8374: "[舜]「Cùng ra nhé, Tsubomi!」[p]",
    8375: "Tsubomi「Vâng ạ! Bắn vào trong em đi!」[p]",
    8376: "Dẫn chuyện|Cả hai cùng đạt đến đỉnh điểm của khoái cảm, ôm chặt lấy nhau trong cơn đê mê.[p]",
    8377: "Tsubomi「Hà... hà... tuyệt vời quá đi...♡」[p]",
    8378: "[舜]「Em vất vả rồi, ngoan lắm」[p]",
    8379: "Tsubomi「Lần sau... lại làm tiếp nhé anh...♡」[p]",
    8380: "[playse storage=\"tubomi/voice_r_tubomi_kaisi2.mp3\" buf=\"2\"]Tsubomi「Hôm nay em sẽ chiều anh hết mình luôn đó nha♡」[p]",
    8381: "[playse storage=\"tubomi/voice_r2_1_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Nào, nằm xuống đi anh... Để em phục vụ cho」[p]",
    8382: "[舜]「Trông em hào hứng ghê nhỉ」[p]",
    8383: "[playse storage=\"tubomi/voice_r2_1_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「Đương nhiên rồi, vì em yêu anh mà♡」[p]",
    8384: "[playse storage=\"tubomi/voice_r2_1_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「Ưm... chui vào rồi nè... ấm áp quá...♡」[p]",
    8385: "[舜]「Cảm giác được em cưỡi lên thích thật đấy」[p]",
    8386: "Tsubomi「Thế thì em sẽ nhấp thật mạnh nhé! A... a...♡」[p]",
    8387: "Dẫn chuyện|Căn phòng tràn ngập âm thanh ướt át và tiếng thở dốc nồng nàn.[p]",
    8388: "Tsubomi「Sướng quá đi mất... anh [舜] ơi...♡」[p]",
    8389: "[舜]「Anh cũng sướng lắm... Sắp không chịu nổi nữa rồi!」[p]",
    8390: "Tsubomi「Bắn vào trong em đi! Đừng ngần ngại gì cả!」[p]",
    8391: "Dẫn chuyện|Dòng tinh dịch ấm nóng lại một lần nữa tưới đẫm vào sâu bên trong cơ thể em ấy.[p]",
    8392: "[playse storage=\"tubomi/voice_r_tubomi_kaisi3.mp3\" buf=\"2\"]Tsubomi「Hôm nay chúng ta đổi tư thế mới nhé?」[p]",
    8393: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Tư thế này... sâu hơn bình thường nhiều lắm á...♡」[p]",
    8394: "[舜]「Thử xem nào, nâng mông cao lên một chút」[p]",
    8395: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「Thế này được chưa anh...? Ưm... vào rồi kìa...♡」[p]",
    8396: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「Á... sâu quá... chạm vào tận cùng luôn rồi...♡」[p]",
    8397: "[舜]「Tư thế từ phía sau này đúng là tuyệt phẩm」[p]",
    8398: "Tsubomi「Mỗi lần anh thúc là người em lại giật nảy lên... sướng tê tái luôn á...♡」[p]",
    8399: "Dẫn chuyện|Từng cú thúc mạnh mẽ khiến Tsubomi chỉ biết bấu chặt lấy ga giường mà rên rỉ.[p]",
    8400: "Tsubomi「A... a... đâm mạnh nữa đi anh... làm em tơi bời đi mà...♡」[p]",
}
