# -*- coding: utf-8 -*-
"""
Part 1 Translations Dictionary - Batch 2 (Lines 8101 - 8250)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P1_DICT_2 = {
    8101: "Tsubomi「A... hà♡ Em là Naruse Tsubomi, 17 tuổi... v-vừa bị vân vê đầu ti... vừa... a...♡」[p]",
    8102: "Tsubomi「Cặp vú này... đang được anh Shun xoa nắn tơi bời đây ạ♡ Ôi...♡ Ôi...♡」[p]",
    8103: "Tsubomi「Ư... hức♡ Đ-Đặc điểm quyến rũ của em là... đôi gò bồng đào mềm mại và nhạy cảm vô cùng này ạ♡」[p]",
    8104: "[舜]「Được đấy, tiếp tục đi. Giới thiệu xem chỗ dâm đãng dưới háng em nhạy cảm thế nào nữa xem nào」[p]",
    8105: "Tsubomi「Hà...♡ Vâng ạ♡ Cô bé của em... mỗi lần được chạm vào ngực là lại rỉ nước nhờn ướt sũng ra ạ♡」[p]",
    8106: "Tsubomi「Chỉ cần được anh Shun đút con cu vào thụt... là em sẽ sướng đến mức phát điên lên mất thôi ạ♡」[p]",
    8107: "Tsubomi「Ôi trời ơi♡ Tuyệt quá... đầu ti tê rần rần lên rồi♡ Em lên đỉnh mất thôi...♡」[p]",
    8108: "[舜]「Tốt lắm, em đậu rồi đấy. Phần thưởng là được anh cho con cu vào nhé」[p]",
    8109: "Tsubomi「Cảm ơn anh nhiều lắm ạ♡ Em muốn con cu của anh đâm nát cô bé của em cơ♡」[p]",
    8110: "Tsubomi「A... a... a...♡ Đút vào rồi♡ Con cu bự quá đi mất♡」[p]",
    8111: "Tsubomi「Hà...♡ Hà...♡ Sướng quá đi... trong bụng em đầy ắp con cu của anh rồi♡」[p]",
    8112: "Tsubomi「Đâm sâu vào nữa đi anh♡ Hãy thụ tinh cho em đi mà♡」[p]",
    8113: "[舜]「Đúng là con bé dâm đãng... thích bị đâm sâu thế này cơ à?」[p]",
    8114: "Tsubomi「Vâng ạ♡ Em thích lắm... em muốn trở thành người đàn bà của anh Shun cơ♡」[p]",
    8115: "Tsubomi「Ôi...♡ Ôi...♡ Nó chạm vào cổ tử cung rồi kìa♡ Sướng điếng cả người luôn á♡」[p]",
    8116: "Tsubomi「A... a...♡ Bắn vào trong đi anh♡ Rót đầy tinh dịch vào trong em đi ạ♡」[p]",
    8117: "[舜]「Bắn nhé... Tsubomi...! Nhận lấy toàn bộ tinh trùng của anh đi!」[p]",
    8118: "Tsubomi「Ư... ôi...♡ Hà...♡ Hà...♡ Để lộ bộ mặt đê mê xấu hổ thế này, em xin lỗi anh nha♡」[p]",
    8119: "Tsubomi「Bị vỗ vào ngực... cô bé của em đã sẵn sàng đón nhận từ lâu rồi nè♡ Mau lên... em muốn có nó ở bên trong cơ♡」[p]",
    8120: "Tsubomi「Vâng ạ♡ Hãy dạy dỗ cô bé của Tsubomi thật nhiều vào đi ạ♡ Đâm thụt gõ phầm phập vào tận đáy sâu nhất luôn đi ạ♡」[p]",
    8121: "Tsubomi「Hức... a...♡ Ôi...♡ Ôi trời ơi♡ Tuyệt quá♡ Nước dâm phun ra... không dừng lại được rồi♡ Nó trào ra kìa♡」[p]",
    8122: "Tsubomi「Hức...♡ Cứ như đang tè dầm vậy á... sướng quá nên nước cứ phun trào xối xả ra thôi♡ Ôi... ôi...♡」[p]",
    8123: "Tsubomi「Ng-Ngón tay...♡ Thụt vào... đâm phầm phập vào đáy sâu thế này em sẽ bị nghiện mất thôi mà♡」[p]",
    8124: "Tsubomi「Tuyệt thật đấy... phụt phụt liên tục mấy lần liền... bên trong bụng em sắp cạn sạch nước luôn rồi nè♡ Ôi...♡ Ôi trời ơi♡」[p]",
    8125: "[舜]「Không sao đâu, cô bé của em nhầy nhụa ướt sũng thế này cơ mà. Muốn phun bao nhiêu nước cứ việc phun ra...」[p]",
    8126: "Tsubomi「A... hức♡ Ôi...♡ Đừng dùng ngón tay ấn mạnh vào tận đáy như thế mà♡ Lại sắp phun ra nữa rồi nè♡ Ôi trời ơi♡」[p]",
    8127: "Tsubomi「A...♡ A... hức♡ Tuyệt quá đi♡ Ôi...♡ Cô bé sướng tê người luôn rồi♡」[p]",
    8128: "[舜]「Giọng em bắt đầu khàn đục dâm đãng hết cả ra rồi đấy. Muốn làm người mẫu mà không biết giữ hình tượng đáng yêu à?」[p]",
    8129: "Tsubomi「Vâng ạ♡ Hà...♡ Lúc này làm sao mà giữ kẽ được nữa chứ ạ♡ A... hức♡ Nước dâm cứ tuôn ra không ngừng được này♡」[p]",
    8130: "Tsubomi「Ôi... ôi trời ơi...♡ Em ra mất♡ Lên đỉnh mất thôi♡ Cô bé đang dâng trào khoái cảm khủng khiếp lắm rồi này♡」[p]",
    8131: "[舜]「Dâm vãi... Tsubomi, em trở nên dâm đãng quá đà rồi đấy... Thế này thì sau này làm sao làm tình kiểu bình thường được nữa hả?」[p]",
    8132: "Tsubomi「Không thể đâu ạ♡ Em đã nếm trải cảm giác làm tình bạo liệt thế này rồi mà♡ Em chỉ muốn bị anh làm cho tơi bời thôi♡」[p]",
    8133: "Tsubomi「A...♡ A...♡ Chỗ đó... lỗ mông được vuốt ve mơn trớn... xấu hổ quá... nó cứ giật giật thắt lại này♡」[p]",
    8134: "[舜]「Nhìn kìa, nó bắt đầu hé mở mấp máy như muốn nuốt chửng ngón tay anh vào trong rồi đấy?」[p]",
    8135: "Tsubomi「Ôi...♡ Ôi trời♡ Được xoa nắn mềm ra rồi...♡ Phía bên trong... cũng muốn được anh vuốt ve nữa cơ♡」[p]",
    8136: "[舜]「À~ nhìn này, nó banh rộng ra rồi kìa... thêm chút nữa là ngón tay lọt vào được rồi. Anh sẽ từ từ nong cho nó quen dần nhé」[p]",
    8137: "Tsubomi「A... hức♡ A...♡ Lỗ mông cũng sắp đút vừa con cu vào rồi này♡ Thế là cả hai lỗ đều được anh sử dụng hết rồi♡」[p]",
    8138: "Tsubomi「Em hạnh phúc lắm... toàn bộ cơ thể em có thể khiến anh [舜] cảm thấy sung sướng... em mong chờ lắm cơ♡」[p]",
    8139: "Tsubomi「Vâng ạ♡ Ôi...♡ Ôi trời ơi♡ Ngón tay... vào trong rồi... nó trơn tuột lọt hẳn vào trong rồi kìa♡」[p]",
    8140: "[舜]「Nếu cô bé phía trước bị đâm lỏng ra, thì lần sau anh sẽ dùng lỗ mông này để kẹp chặt con cu đấy nhé」[p]",
    8141: "Tsubomi「Em hiểu rồi ạ♡ Em nghe lời anh hết♡ Cả cô bé lẫn lỗ mông của Tsubomi, xin anh hãy tận tình sử dụng hết đi ạ♡」[p]",
    8142: "Tsubomi「Hức... a...♡ Ôi...♡ Ôi trời ơi♡ Bên trong lỗ mông... đang được mơn trớn kìa♡ Hức...♡」[p]",
    8143: "Tsubomi「Ư... hức♡ Hà, a...♡ Chỉ mới một ngón tay thôi mà đã đầy ắp rồi nè♡ Ôi, ôi trời ơi♡」[p]",
    8144: "[舜]「Kinh thật, nó thắt chặt ghê gớm luôn ấy... Nếu đút con cu vào được đây thì chắc sướng tê người luôn cho xem」[p]",
    8145: "Tsubomi「Hức...♡ A...♡ A...♡ Tới rồi♡ Chạm vào tận sâu bên trong rồi kìa♡ Cho em thêm nữa đi anh♡」[p]",
    8146: "Tsubomi「Dùng đầu khấc thúc mạnh vào tận sâu bên trong đi anh...♡ Em muốn anh khuấy đảo thật nhiều cơ...♡ A... a...♡」[p]",
    8147: "Tsubomi「Ôi...♡ Ôi...♡ Ôi trời♡ Vì quá thèm thuồng nên em càng lúc càng trở nên dâm đãng mất rồi nè♡」[p]",
    8148: "Tsubomi「Hà...♡ Hà...♡ Ư... hức♡ Từng đường gân guốc nổi cộm trên con cu đang cọ sát rần rật vào trong em kìa♡」[p]",
    8149: "Tsubomi「Cả nhiệt độ, kích thước lẫn độ cứng em đều cảm nhận rõ mồn một luôn♡ Sướng quá♡ Quan hệ trần không bao tuyệt vời quá đi♡」[p]",
    8150: "Tsubomi「Cứ thế này em sẽ bị nghiện mất thôi mà♡ Ôi...♡ Ư... ôi...♡ Đáy bụng em bị chèn ép căng tức cả ra rồi♡」[p]",
    8151: "Tsubomi「Ư... ôi...♡ Ôi trời ơi♡ Cứ rút ra đút vào chậm rãi như đang trêu ngươi thế này... tuyệt vời quá đi anh ơi♡」[p]",
    8152: "[舜]「Em kẹp chặt kinh khủng vậy... đang nũng nịu đòi anh bắn tinh vào trong đúng không hả?」[p]",
    8153: "Tsubomi「Đúng thế đấy ạ♡ Em muốn anh bắn vào trong... rót thật nhiều tinh trùng vào cho em đi mà♡ Mau lên anh♡」[p]",
    8154: "Tsubomi「Ôi... ôi trời ơi...♡ Hà, hà... Ý định muốn gieo giống cho em của anh truyền thẳng sang em rồi này♡」[p]",
    8155: "Tsubomi「Ư... hức♡ Hà, hà, em đã chuẩn bị sẵn sàng hết rồi... chỉ chờ được anh rót đầy vào thôi nè♡」[p]",
    8156: "Tsubomi「N-Nếu là lúc này... em sẽ thực sự được anh gieo giống mất thôi♡ Toàn bộ hạt giống của anh, em sẽ đón nhận hết♡」[p]",
    8157: "Tsubomi「Tuyệt quá đi♡ Con cu của anh... đang bung hết sức ra rồi kìa♡ Như muốn quyết tâm thụ tinh cho em bằng được vậy... cuồng bạo quá♡」[p]",
    8158: "Tsubomi「A...♡ Hức...♡ Ôi...♡ Cô bé của em đang mừng rỡ reo vui này♡ Đang chuẩn bị để hứng trọn dòng tinh dịch rồi nè♡」[p]",
    8159: "Tsubomi「Ư... hức♡ N-Nếu bây giờ bắn vào... em sẽ hứng trọn toàn bộ tinh trùng mất♡ Sẽ thụ thai mất thôi♡」[p]",
    8160: "[舜]「À~ chỉ đưa hông để thụ tinh cho em thôi mà sướng thế này cơ mà...! Cứ thế này bắn thẳng vào nơi sâu nhất nhé?」[p]",
    8161: "Tsubomi「Ôi...♡ A...♡ Bắn vào đi anh♡ Giữ chặt lấy hông em rồi bắn ừng ực vào tận đáy sâu nhất đi ạ♡」[p]",
    8162: "Tsubomi「Ưm...♡ Ôi trời ơi♡ Em muốn anh rót thẳng trực tiếp vào tận tử cung cơ mà♡ Hãy bắn thật mạnh vào nhé♡」[p]",
    8163: "Tsubomi「A... a...♡ Cảm giác như toàn bộ ruột gan trong bụng sắp bị kéo tuột ra ngoài vậy...♡ Con cu cứ móc sâu vào──」[p]",
    8164: "Tsubomi「Bên trong bị khuấy đảo nhão nhoét hết cả ra rồi này♡ Ôi...♡ Em chưa bao giờ biết cảm giác mãnh liệt đến thế này đâu♡」[p]",
    8165: "Tsubomi「Ôi...♡ Ôi...♡ Phải làm sao đây... cả trong đầu lẫn thể xác... như sắp nổ tung vỡ vụn ra mất thôi♡」[p]",
    8166: "Tsubomi「Hức... a...♡ Ôi trời♡ Con cu đang giật giật quẫy đạp dữ dội bên trong kìa♡ Cô bé của em không kìm hãm nổi nữa rồi♡」[p]",
    8167: "Tsubomi「Thành bên trong bị cọ sát nát bấy... cứ thế này thì em sẽ lên đỉnh ngay mất thôi♡ Em sắp phát điên lên rồi♡」[p]",
    8168: "Tsubomi「Hà...♡ Hà...♡ Hà...♡ Cơ thể em càng ngày càng biến thành hình dáng dành riêng cho anh mất rồi... Hạnh phúc quá đi mà♡」[p]",
    8169: "[舜]（…Có vẻ như sắp tỉnh rồi… Cứ tiếp tục thế này có ổn không đây…？）[p]",
    8170: "Nagi「Ưm…………」[p]",
    8171: "[舜]「Bắn ra rồi…! Nagi…!」[p]",
    8172: "[舜]「Phù, phù, phù… Thân thể Nagi… ướt sũng dính đầy tinh dịch của mình rồi kìa… A, dâm đãng thật sự…」[p]",
    8173: "Nagi「Ưm… hức…」[p]",
    8174: "[舜]（Chết tiệt… Tỉnh dậy rồi sao? À không… Có vẻ vẫn ổn… May quá）[p]",
    8175: "[舜]「Bắn ra rồi…! Nagi…! Khốn thật!」[p]",
    8176: "[舜]（Oa, vì nhịn lâu ngày nên bắn ra nhiều kinh khủng……）[p]",
    8177: "[舜]（A, chảy dọc theo khe rãnh, cả hột le lẫn âm đạo… đều nhầy nhụa tinh dịch rồi……）[p]",
    8178: "[舜]（Hoàn toàn khác hẳn với hồi còn nhỏ… Đã trưởng thành thành một cơ thể gợi cảm thế này rồi… A~, chỗ nào trông cũng mềm mại hết…）[p]",
    8179: "Nagi「Khò… khò… khò…」[p]",
    8180: "[舜]「Chẳng có dấu hiệu gì là sắp tỉnh dậy cả…」[p]",
    8181: "[舜]（Thân thể này Hayato đã làm đủ trò rồi sao… A~, nghĩ tới lại thấy bực mình…）[p]",
    8182: "[舜]（Mình cũng sẽ sờ nắn cặp ngực này thỏa thích. A, đầu ti cũng bắt đầu cương lên rồi… Lát nữa phải vuốt ve mơn trớn thật kỹ mới được）[p]",
    8183: "Nagi「Ưm… phù…」[p]",
    8184: "[舜]（Hết cả hồn… Cứ tưởng tỉnh dậy rồi chứ… Ổn rồi, vẫn còn đang ngủ say… Phải nhìn cho thật kỹ mới được）[p]",
    8185: "[舜]（Quần lót thít chặt vào, làm lộ rõ mồn một khe rãnh… Hê, chỗ này trông khá là múp míp đấy chứ）[p]",
    8186: "[舜]（Giờ thì… bên trong quần lót trông thế nào nhỉ…? Ưm, …Khe rãnh khép khít rịt lại kìa）[p]",
    8187: "[舜]（Dùng ngón tay vạch ra để chiêm ngưỡng nào…… Kìa? Tận sâu bên trong… là màng trinh sao…? ……Không, làm sao có chuyện đó được）[p]",
    8188: "[舜]（Bên trong cũng là một màu hồng hào tuyệt đẹp. …Hột le cũng nở nang chúm chím… Đẹp thật đấy）[p]",
    8189: "[舜]（Bất ngờ bị vạch ra nên cơ thể giật mình chăng? Cứ co giật khẽ khàng thế này trông đáng yêu ghê…）[p]",
    8190: "[舜]（Phải quan sát thật kỹ tận sâu bên trong mới được… Bên trong trông chật hẹp quá… Chắc nhét một ngón tay vào thôi cũng chật ních rồi）[p]",
    8191: "[舜]（Nong cho quen thôi chắc cũng vất vả lắm đây… Nhưng độ khít khao chắc chắn sẽ tuyệt vời lắm cho xem……）[p]",
    8192: "[舜]「Nagi…… Chụt…。 Đôi môi mềm mại quá…」[p]",
    8193: "[舜]「Hà… Môi em ấy lại mềm đến mức này sao… Cứ đà này mình không dừng lại được mất」[p]",
    8194: "[舜]「Nagi, một lần nữa nhé…。 Chụt mút…… Chụt…… Ưm, phù」[p]",
    8195: "Nagi「Ưm, phù… Ưm」[p]",
    8196: "[舜]「A, khó thở lắm đúng không… Anh xin lỗi nhé. Hì hì, thế này mà vẫn chưa tỉnh sao…」[p]",
    8197: "[舜]「Cho anh luồn lưỡi vào trong miệng nhé. Cùng hôn sâu quấn lưỡi nào… Chụt, mút… Chụt……」[p]",
    8198: "Nagi「Ưm, phù… Ưm…」[p]",
    8199: "[舜]（A, lưỡi của Nagi nóng hổi ướt át quá… Lại còn rên rỉ giọng điệu dâm đãng thế này nữa… Chịu không nổi mất…）[p]",
    8200: "[舜]「Ngực em… Oa, mềm mại như bông… Mềm quá… A~, cảm giác sờ vào thích thật đấy…」[p]",
    8201: "[舜]（Kinh thật, chỉ cần dùng chút lực là mềm đến mức biến dạng luôn rồi）[p]",
    8202: "[舜]（Hồi nhỏ thì gầy gò và bé tí teo. Không ngờ lại lớn thành cặp ngực gợi tình đến nhường này…）[p]",
    8203: "[舜]（Vừa tóm chặt lấy vừa nhào nặn thế này, sướng thật… Trông chẳng khác nào đang cưỡng bức người ta cả）[p]",
    8204: "Nagi「Ưm… Ư… hà…」[p]",
    8205: "[舜]「Hử… Đang ngủ mà cũng thấy sướng sao? Nagi dâm đãng thật đấy nhé…」[p]",
    8206: "[舜]（Đầu ti cũng cương cứng lên rồi. Nếu vân vê thì sẽ thế nào nhỉ?）[p]",
    8207: "Nagi「A… Hà… A, a…」[p]",
    8208: "[舜]（Ngủ say mà vẫn cảm nhận được khoái cảm cơ à… Nagi, thực ra em cũng dâm ngầm lắm đấy chứ…）[p]",
    8209: "[舜]（Khe rãnh phía dưới thế nào rồi nhỉ…… Nóng ran… Ơ, hình như có gì đó nhờn nhờn ươn ướt. Ra nước rồi sao?）[p]",
    8210: "Nagi「Khò…… Khò……」[p]",
    8211: "[舜]（…Hê, dù đang ngủ nhưng cơ thể vẫn tự động phản ứng lại cơ đấy. Chẳng khác gì cơ thể đàn ông cả）[p]",
    8212: "[舜]（Hột le cũng nở to lên rồi…… Nagi, chỗ này làm em sướng lắm đúng không?）[p]",
    8213: "Nagi「Ưm…♡ Ưm……♡ Phù, ưm…」[p]",
    8214: "[舜]（Cơ thể em ấy khẽ giật giật, hơi thở dồn dập hẳn lên. Đang mơ thấy giấc mơ ướt át nào chăng…）[p]",
    8215: "[舜]（Khe rãnh đã ướt sũng nhầy nhụa rồi…。 Bị khuấy đảo ướt át đến thế này mà vẫn không tỉnh dậy cơ đấy…）[p]",
    8216: "Nagi「Ưm♡ Hà…♡ Hà…♡」[p]",
    8217: "[舜]（Cơ thể em ấy đã bước vào trạng thái động dục rồi… Nagi, anh thèm đút vào trong em lắm rồi đấy……）[p]",
    8218: "[舜]「Ư, …Oa! Sướng quá… Chỉ mới áp sát vào khe rãnh cọ qua cọ lại thôi mà đã sướng đến mức này rồi sao…」[p]",
    8219: "[舜]「A~, hông mình cứ tự động đưa đẩy… Hà, a, khe rãnh của Nagi cũng đang co bóp giật giật kìa」[p]",
    8220: "Nagi「Khò… Khò…… Ưm」[p]",
    8221: "[舜]「Sắp ra rồi…! Nagi…! Bắn vào nhé…!」[p]",
    8222: "Nagi「Ưm… A…♡」[p]",
    8223: "[舜]（Bắn hết sạch lên người em ấy rồi… Trông gợi cảm không chịu nổi）[p]",
    8224: "[舜]（Lần sau, mình nhất định sẽ đút thẳng vào tận sâu bên trong…）[p]",
    8225: "Nagi「Ư… ưm……」[p]",
    8226: "[舜]「Ngủ ngon nhé, Nagi…」[p]",
    8227: "[舜]「Tsubomi, hôm nay tiếp tục luyện tập chứ?」[p]",
    8228: "Tsubomi「Vâng ạ! Em sẵn sàng rồi!」[p]",
    8229: "[舜]「Nào, tấn công thử xem」[p]",
    8230: "Tsubomi「Hây a!」[p]",
    8231: "[舜]「Chậm quá!」[p]",
    8232: "Tsubomi「Á!」[p]",
    8233: "Dẫn chuyện|Tôi xoay người tóm lấy cánh tay Tsubomi rồi đè em ấy xuống sàn.[p]",
    8234: "Tsubomi「Đau quá à… Anh [舜] chẳng chịu nương tay gì cả…」[p]",
    8235: "[舜]「Đã là luyện tập thì phải nghiêm túc chứ」[p]",
    8236: "Tsubomi「Nhưng mà… tư thế này… xấu hổ quá…」[p]",
    8237: "Dẫn chuyện|Hai chân em ấy bị tách rộng sang hai bên, để lộ chiếc quần đùi ngắn cũn cỡn.[p]",
    8238: "[舜]「Xấu hổ gì chứ, tập võ thì phải thế này」[p]",
    8239: "Tsubomi「Ư… tay anh… chạm vào đâu thế…」[p]",
    8240: "[舜]「Kiểm tra cơ bắp thôi mà. Đùi trong của em mềm thật đấy」[p]",
    8241: "Tsubomi「A… nhột quá… đừng sờ vào đó mà…」[p]",
    8242: "[舜]「Tim em đập nhanh thế? Hưng phấn rồi à?」[p]",
    8243: "Tsubomi「K-Không có mà…!」[p]",
    8244: "Dẫn chuyện|Tôi khẽ luồn tay qua lớp vải mỏng, chạm vào vùng đùi non mịn màng.[p]",
    8245: "Tsubomi「A… ưm… anh [舜]…」[p]",
    8246: "[舜]「Chỗ này… bắt đầu nóng lên rồi đấy」[p]",
    8247: "Tsubomi「Đừng mà… em không tập trung được mất…」[p]",
    8248: "[舜]「Thế thì nghỉ tập nhé, chuyển sang chuyện khác thú vị hơn」[p]",
    8249: "Tsubomi「Chuyện… khác ư…?」[p]",
    8250: "[舜]「Ừ, chuyện làm em thấy sướng hơn nhiều」[p]"
}
