# -*- coding: utf-8 -*-
"""
Part 1 Translations Dictionary - Batch 5 (Lines 8401 - 8545)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P1_DICT_5 = {
    8401: "Tsubomi「Đâm sâu nữa đi anh... Tới tận cùng luôn đi mà...♡」[p]",
    8402: "[舜]「Bên trong em co bóp dữ dội quá... Sướng đến muốn phát điên rồi đây!」[p]",
    8403: "Tsubomi「Ưm... Tinh dịch của anh nóng hổi quá... Cứ như đang thiêu đốt bên trong em vậy...♡」[p]",
    8404: "[舜]「Đó là vì tinh dịch được nấu sôi sùng sục trong tinh hoàn đấy mà... Hãy cảm nhận xem anh đã hưng phấn đến mức nào đi」[p]",
    8405: "Tsubomi「Phù...♡ Phù...♡ Cứ nghĩ đến chuyện anh vì em mà hưng phấn đến thế này... Là em thấy sướng vô cùng luôn ý...♡」[p]",
    8406: "Tsubomi「Ôi... ôi trời ơi...♡ Tuyệt quá... Khắp người em dính đầy tinh dịch nhớp nháp rồi nè♡ Nóng hổi và nhầy nhụa ghê á♡」[p]",
    8407: "Tsubomi「Anh chỉ nhìn mỗi mình em, vì một mình em mà bắn ra đúng không...? Được độc chiếm anh thế này em hạnh phúc lắm...♡」[p]",
    8408: "Tsubomi「Thực ra thì em vừa muốn anh rót vào bên trong, vừa muốn anh bắn cả vào trong miệng em nữa cơ đấy♡」[p]",
    8409: "[舜]「A... Sắp ra rồi...! Nào... Muốn anh bắn vào trong thì phải ngoan ngoãn làm nũng cho đàng hoàng chứ!」[p]",
    8410: "Tsubomi「Vâng ạ♡ A...♡ X-Xin anh... Hãy bắn vào bên trong em đi ạ...♡」[p]",
    8411: "[舜]「Nói thế mà đòi anh bắn cho đấy à...!? Đã bảo là phải làm nũng dâm đãng hơn nữa cơ mà!」[p]",
    8412: "Tsubomi「Ưm... ôi♡ Xin anh hãy gieo giống tinh trùng của anh [舜] vào cô bé của Tsubomi đi ạ♡ Cô bé của em đã sẵn sàng đón nhận rồi ạ♡」[p]",
    8413: "[舜]「Hà, hà... Dù anh muốn em nói bậy bạ hơn nữa cơ nhưng... thế này cũng được rồi... Bắn đây! Khốn thật, a, a... a!」[p]",
    8414: "Tsubomi「Hức... a...♡ Ôi... Ôi trời ơi♡ Bắn phì phì từng đợt vào trong rồi kìa♡ Em được anh gieo giống rồi nè♡」[p]",
    8415: "[舜]「A~ kinh thật... Hà, tuyệt đỉnh... Sướng quá đến mức suýt thì khuỵu cả chân luôn rồi này...」[p]",
    8416: "Tsubomi「Ư... hức♡ Chưa bắn hết thì không được rút ra đâu đấy...! Phải trút sạch toàn bộ vào bên trong em rồi mới được rút ra cơ♡」[p]",
    8417: "Tsubomi「Hức... a...♡ Ôi...♡ Bụng em căng tức đầy ắp cả rồi nè♡ Sắp trào ngược ra ngoài luôn rồi á♡」[p]",
    8418: "Tsubomi「Hà...♡ Hà...♡ Hà...♡ Bị rót vào một lượng khổng lồ thế này... Thì em sẽ biến thành mẹ trẻ con thật mất thôi♡」[p]",
    8419: "[舜]「Chẳng phải em luôn thèm muốn được gieo giống còn gì...! Nhìn kìa, trào ra ngoài rồi... Phải giữ nguyên thế này để bịt kín lại một lúc mới được」[p]",
    8420: "[playse storage=\"tubomi/voice_r_tubomi_kaisi2.mp3\" buf=\"2\"]Tsubomi「Em làm sao biết cách làm nũng thế nào chứ... Dạy em cách làm nũng đi mà♡」[p]",
    8421: "[舜]「Phù... Hà, hà... Giờ đút con cu vào được rồi đúng không? Nào, làm nũng đi xem nào?」[p]",
    8422: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou1.mp3\" buf=\"2\"]Tsubomi「Hà...♡ Hà...♡ Vâng ạ♡ A... Tuyệt quá♡ Em muốn con cu cong vút cương cứng này cơ♡」[p]",
    8423: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou2.mp3\" buf=\"2\"]Tsubomi「Cho em đi... Đút ngập vào cô bé của Tsubomi đi...♡ Cắm khít khao tới tận đáy sâu nhất... Rồi dập thụt liên tục cho em đi mà♡」[p]",
    8424: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou3.mp3\" buf=\"2\"]Tsubomi「Hà♡ Hà♡ Mau lên... Em muốn nếm trải khoảnh khắc con cu nở to bên trong... Hãy bắn dòng tinh dịch nóng hổi vào trong em đi」[p]",
    8425: "[舜]「Dâm vãi, thế này thì anh không nương tay được nữa rồi... Anh sẽ đâm một mạch tới tận đáy sâu nhất luôn đấy...! Nào, thưởng thức đi!」[p]",
    8426: "[playse storage=\"tubomi/voice_r2_2_tubomi_sou4.mp3\" buf=\"2\"]Tsubomi「A... a... a...♡ Ôi...♡ Ôi trời ơi♡ To quá♡ Cô bé của em sắp bị phá hỏng mất thôi♡」[p]",
    8427: "[舜]「A, sắp ra mất rồi...! Tsubomi... Vẩy tung tóe khắp người em được đúng không hả!?」[p]",
    8428: "Tsubomi「Được chứ ạ♡ Cứ làm theo ý anh [舜] thích đi... Toàn bộ cơ thể em đã là của anh [舜] từ lâu rồi mà♡」[p]",
    8429: "[舜]「Anh biết em sẽ nói thế mà... Nào! Chuẩn bị đón nhận tinh trùng bằng cả cơ thể đi...! Xuất đây...!」[p]",
    8430: "Tsubomi「Tới đi anh...♡ Cứ việc bắn thỏa thích cho nhầy nhụa khắp người em đi ạ♡」[p]",
    8431: "[舜]「Khốn thật... Ra đây! A, a... a...!」[p]",
    8432: "Tsubomi「A... a... a...♡ Ôi...♡ Ôi trời ơi♡ Nước trắng đục bắn lên người em rồi kìa♡ Phù...♡ Cuối cùng cũng tới rồi♡」[p]",
    8433: "[舜]「Bắn ra đặc quánh luôn này... Tất cả là nhờ Tsubomi biết nịnh nọt con cu của anh đấy nhé...」[p]",
    8434: "Tsubomi「Hà...♡ Hà...♡ Được anh khen rồi kìa♡ Hạnh phúc quá...♡ Em sẽ học cách làm nũng giỏi hơn nữa cho anh xem♡」[p]",
    8435: "Tsubomi「Hức... a...♡ Ôi trời ơi♡ Tuyệt quá... Toàn thân dính đầy tinh dịch hết cả rồi...♡」[p]",
    8436: "Tsubomi「Hà♡ Hà♡ Mùi nồng đến mức choáng váng cả đầu... Mùi hương của con đực... Đang muốn làm em mang bầu đây mà♡」[p]",
    8437: "Tsubomi「Tinh trùng cũng... Đặc quánh và sánh mịn ghê♡ Thế này mà... Bị bắn vào tận sâu bên trong thì chắc biến thành mẹ trẻ con ngay mất thôi♡」[p]",
    8438: "Tsubomi「Hà♡ A...♡ Phù♡ Bắn vào bên trong đi anh♡ Em muốn anh rót tinh trùng nóng hổi mới ra vào tận sâu đáy cùng cơ♡」[p]",
    8439: "[舜]「Quả nhiên là em đã hoàn toàn biến thành một ả đàn bà dâm đãng rồi đấy nhỉ! Nào, muốn anh bắn vào trong thì biết phải nịnh bợ thế nào rồi chứ!」[p]",
    8440: "Tsubomi「Cô bé non tơ mơn mởn và túi chứa hạt giống đã chuẩn bị sẵn sàng hết rồi đây ạ♡ Mau bắn phì phì vào trong em đi ạ♡」[p]",
    8441: "[舜]「Khốn thật... A, tuyệt đỉnh...! Anh sẽ bắn thật nhiều cho đến khi ngập tràn bên trong mới thôi...! Đón nhận cho cẩn thận đấy...!」[p]",
    8442: "Tsubomi「A... hức♡ Dòng tinh dịch nóng hổi đang tràn vào tận sâu bên trong em rồi kìa♡ Ôi trời, may mà em đã làm nũng anh♡」[p]",
    8443: "Tsubomi「Cuối cùng cũng đón nhận được rồi♡ Cảm ơn anh vì đã lấp đầy cơ thể em thế này ạ♡」[p]",
    8444: "Tsubomi「Hà...♡ Hà...♡ A, có khi tinh trùng đã chạm tới nơi sâu nhất trong bụng em rồi cũng nên♡ Thụ thai mất rồi♡」[p]",
    8445: "Tsubomi「Ôi...♡ Ôi trời ơi...♡ Tuyệt quá♡ Th-Thực sự là ngập tràn bên trong rồi kìa♡」[p]",
    8446: "Tsubomi「Hức... Trào ra ngoài rồi kìa♡ Tinh dịch chảy tràn ra uổng phí quá đi mất♡」[p]",
    8447: "Tsubomi「Dùng con cu bịt kín lại để không bị tràn ra ngoài đi anh♡ Em muốn giữ cho nó luôn đầy ắp bên trong cơ♡」[p]",
    8448: "[playse storage=\"tubomi/voice_j_tubomi_zettyou1_1.mp3\" buf=\"2\"]Tsubomi「Đừng mà... Không chịu đâu... Khoái cảm đang dâng trào lên rồi... Em sắp phát điên mất thôi! A... a... a...!」[p]",
    8449: "[舜]「Trông em lên đỉnh có vẻ sướng lắm nhỉ」[p]",
    8450: "[playse storage=\"tubomi/voice_j_tubomi_zettyou1_2.mp3\" buf=\"2\"]Tsubomi「Hà, hà... Bộ dạng em lúc này trông xấu xí lắm... Tóc tai rối bời cả ra rồi này...」[p]",
    8451: "[舜]「Đâu có, trông em gợi cảm và đáng yêu lắm mà」[p]",
    8452: "[playse storage=\"tubomi/voice_j_tubomi_zettyou2_1.mp3\" buf=\"2\"]Tsubomi「A... a... lại tới nữa rồi! Không dừng lại được đâu! Lên đỉnh mất thôi!」[p]",
    8453: "[舜]「Cứ việc lên đỉnh thỏa thích đi, Tsubomi」[p]",
    8454: "[playse storage=\"tubomi/voice_j_tubomi_zettyou2_2.mp3\" buf=\"2\"]Tsubomi「Hức... sướng quá đi mất... Toàn thân em run rẩy hết cả lên rồi này...♡」[p]",
    8455: "[舜]「Thế mới là Tsubomi của anh chứ」[p]",
    8456: "[playse storage=\"tubomi/voice_r_tubomi_zettyou1_1.mp3\" buf=\"2\"]Tsubomi「Á... chỗ đó... đừng chọc ngoáy vào mà... Em ra mất thôi!」[p]",
    8457: "[舜]「Chỗ này nhạy cảm lắm đúng không?」[p]",
    8458: "[playse storage=\"tubomi/voice_r_tubomi_zettyou1_2.mp3\" buf=\"2\"]Tsubomi「Vâng ạ... Nhột lắm... Nhưng mà sướng vô cùng luôn á...♡」[p]",
    8459: "[舜]「Ngoan lắm, để anh làm cho em sướng hơn nữa nhé」[p]",
    8460: "[playse storage=\"tubomi/voice_r_tubomi_zettyou2_1.mp3\" buf=\"2\"]Tsubomi「A... a... a... không chịu nổi nữa rồi! Ra rồi, em bắn nước ra mất rồi!」[p]",
    8461: "[舜]「Phun ra nhiều nước thế này cơ à? Tuyệt thật đấy」[p]",
    8462: "[playse storage=\"tubomi/voice_r_tubomi_zettyou2_2.mp3\" buf=\"2\"]Tsubomi「Xấu hổ chết đi được... Anh [舜] biến em thành đứa dâm đãng mất rồi...♡」[p]",
    8463: "[舜]「Nhưng em thích thế đúng không?」[p]",
    8464: "Tsubomi「Vâng... Em thích lắm... Em nghiện anh mất rồi...♡」[p]",
    8465: "[playse storage=\"tubomi/voice_h_tubomi_gauge1.mp3\" buf=\"2\"]Tsubomi「Ưm... anh chạm vào chỗ đó làm tim em đập nhanh quá...」[p]",
    8466: "[playse storage=\"tubomi/voice_h_tubomi_gauge2.mp3\" buf=\"2\"]Tsubomi「A... nhột quá à... Đừng trêu em nữa mà...♡」[p]",
    8467: "[playse storage=\"tubomi/voice_h_tubomi_gauge3.mp3\" buf=\"2\"]Tsubomi「Hà... hà... Người em nóng ran lên rồi này...」[p]",
    8468: "[playse storage=\"tubomi/voice_h_tubomi_gauge4.mp3\" buf=\"2\"]Tsubomi「Chỗ đó... ướt nhẹp hết cả rồi... Tại anh hết đấy...♡」[p]",
    8469: "[playse storage=\"tubomi/voice_h_tubomi_gauge5.mp3\" buf=\"2\"]Tsubomi「Nhanh lên đi anh... Em muốn anh chạm vào sâu hơn nữa cơ...」[p]",
    8470: "[playse storage=\"tubomi/voice_h_tubomi_gauge6.mp3\" buf=\"2\"]Tsubomi「A... ưm... sướng quá đi mất... Em không chịu nổi nữa đâu...♡」[p]",
    8471: "[playse storage=\"tubomi/voice_h_tubomi_gauge7.mp3\" buf=\"2\"]Tsubomi「Đút vào đi anh! Em thèm con cu của anh lắm rồi!」[p]",
    8472: "[playse storage=\"tubomi/voice_h_tubomi_gauge8.mp3\" buf=\"2\"]Tsubomi「A... a... chạm tới tận cùng rồi... Sướng điên lên mất thôi!」[p]",
    8473: "[playse storage=\"tubomi/voice_h_tubomi_gauge9.mp3\" buf=\"2\"]Tsubomi「Mạnh nữa lên anh! Đâm nát cô bé của em đi!」[p]",
    8474: "[playse storage=\"tubomi/voice_h_tubomi_gauge10.mp3\" buf=\"2\"]Tsubomi「Ra mất... Em sắp lên đỉnh rồi... Cùng ra nhé anh!」[p]",
    8475: "[playse storage=\"tubomi/voice_h_tubomi_gauge11.mp3\" buf=\"2\"]Tsubomi「Hức... a... ngập tràn tinh dịch bên trong rồi... Tuyệt vời quá...♡」[p]",
    8476: "[playse storage=\"tubomi/voice_h_tubomi_gauge12.mp3\" buf=\"2\"]Tsubomi「Em yêu anh [舜] nhiều lắm... Mãi mãi là của anh thôi...♡」[p]",
    8477: "[playse storage=\"tubomi/voice_h_tubomi_gauge13.mp3\" buf=\"2\"]Tsubomi「Lần sau lại làm cho em sướng thế này nữa nhé anh...♡」[p]",
    8478: "[playse storage=\"tubomi/voice_h_tubomi_gauge14.mp3\" buf=\"2\"]Tsubomi「Ưm... nằm nghỉ với em một lát đã nào...」[p]",
    8479: "[playse storage=\"tubomi/voice_h_tubomi_gauge15.mp3\" buf=\"2\"]Tsubomi「Ôm em chặt vào đi anh... Em thích mùi của anh lắm♡」[p]",
    8480: "[playse storage=\"tubomi/voice_h_tubomi_gauge16.mp3\" buf=\"2\"]Tsubomi「Hì hì, hôm nay em ngoan đúng không nè? Thưởng cho em đi chứ♡」[p]",
    8481: "[playse storage=\"tubomi/voice_h_tubomi_gauge17.mp3\" buf=\"2\"]Tsubomi「Hôn em một cái nữa đi mà... Chụt♡」[p]",
    8482: "[playse storage=\"tubomi/voice_h_tubomi_gauge18.mp3\" buf=\"2\"]Tsubomi「A... anh lại cương lên rồi kìa... Thích thế không biết♡」[p]",
    8483: "[playse storage=\"tubomi/voice_h_tubomi_gauge19.mp3\" buf=\"2\"]Tsubomi「Lại muốn làm hiệp nữa sao? Em chiều anh hết luôn đấy♡」[p]",
    8484: "[playse storage=\"tubomi/voice_h_tubomi_gauge20.mp3\" buf=\"2\"]Tsubomi「Nào, đút vào trong em đi anh... Em sẵn sàng rồi!」[p]",
    8485: "[playse storage=\"tubomi/voice_h_tubomi_gauge21.mp3\" buf=\"2\"]Tsubomi「A... a... lại vào trong rồi... Ấm áp quá đi...♡」[p]",
    8486: "[playse storage=\"tubomi/voice_h_tubomi_gauge22.mp3\" buf=\"2\"]Tsubomi「Hiệp hai này cảm giác còn mãnh liệt hơn hiệp một nữa á!」[p]",
    8487: "[playse storage=\"tubomi/voice_h_tubomi_gauge23.mp3\" buf=\"2\"]Tsubomi「Thúc mạnh vào đi anh! Đừng thương tiếc gì em cả!」[p]",
    8488: "[playse storage=\"tubomi/voice_h_tubomi_gauge24.mp3\" buf=\"2\"]Tsubomi「A... a... sướng quá... Em sắp không thở nổi rồi nè...♡」[p]",
    8489: "[playse storage=\"tubomi/voice_h_tubomi_gauge25.mp3\" buf=\"2\"]Tsubomi「Bắn vào đi! Bắn đầy bụng em đi anh [舜] ơi!」[p]",
    8490: "[playse storage=\"tubomi/voice_h_tubomi_gauge26.mp3\" buf=\"2\"]Tsubomi「Hức... tinh dịch lại trào ra nữa rồi... Sướng mê ly luôn...♡」[p]",
    8491: "[playse storage=\"tubomi/voice_h_tubomi_gauge27.mp3\" buf=\"2\"]Tsubomi「Hà... hà... em kiệt sức mất rồi... Nhưng mà hạnh phúc lắm...♡」[p]",
    8492: "[playse storage=\"tubomi/voice_h_tubomi_gauge28.mp3\" buf=\"2\"]Tsubomi「Cảm ơn anh vì đã yêu thương em nhiều đến thế này nhé♡」[p]",
    8493: "[playse storage=\"tubomi/voice_h_tubomi_gauge29.mp3\" buf=\"2\"]Tsubomi「Ngủ thôi anh... Mai chúng ta lại tiếp tục nhé♡」[p]",
    8494: "[playse storage=\"tubomi/voice_h_tubomi_gauge30.mp3\" buf=\"2\"]Tsubomi「Chúc anh ngủ ngon... Anh [舜] của em♡」[p]",
    8495: "[playse storage=\"tubomi/voice_h_tubomi_gauge31.mp3\" buf=\"2\"]Tsubomi「Yêu anh nhất trên đời luôn đó nha... Chụt♡」[p]",
    8496: "Tsubomi「Đ-Đây là lần đầu tiên của em đấy... Anh phải nhẹ nhàng thôi nhé...」[p]",
    8497: "[舜]「Anh biết rồi, đừng lo lắng quá」[p]",
    8498: "Tsubomi「Ưm... Em hơi sợ một chút... Nhưng vì là anh [舜] nên em sẵn sàng rồi」[p]",
    8499: "[舜]「Cảm ơn em đã tin tưởng anh, Tsubomi」[p]",
    8500: "Tsubomi「N-Nó... đang chạm vào rồi kìa... To quá...」[p]",
    8501: "[舜]「Thả lỏng ra nào, hít thở sâu vào」[p]",
    8502: "Tsubomi「Hà... phù... Ưm... đau một chút... nhưng không sao đâu ạ」[p]",
    8503: "[舜]「Vào được một nửa rồi đấy... Em ổn chứ?」[p]",
    8504: "Tsubomi「Vâng... Tiếp tục đi anh... Đút hết vào đi ạ」[p]",
    8505: "Dẫn chuyện|Tôi từ từ tiến sâu vào bên trong, cảm nhận sự chật chội và nóng bỏng của màng trinh trinh nguyên.[p]",
    8506: "Tsubomi「A... vào hết rồi... Đầy ắp bên trong em rồi kìa...♡」[p]",
    8507: "[舜]「Tsubomi ngoan lắm, giờ bắt đầu cử động nhé」[p]",
    8508: "Tsubomi「Ưm... Chậm rãi thôi anh nhé...♡」[p]",
    8509: "Dẫn chuyện|Từng nhịp chuyển động nhẹ nhàng dần xua tan cơn đau, thay thế bằng cảm giác tê dại ngọt ngào.[p]",
    8510: "Tsubomi「A... nhột quá... Nhưng mà... Bắt đầu thấy sướng rồi nè...♡」[p]",
    8511: "[舜]「Thế thì anh tăng tốc nhé」[p]",
    8512: "Tsubomi「Vâng ạ! Hãy làm cho lần đầu tiên của em trở nên đáng nhớ nhất đi!」[p]",
    8513: "Dẫn chuyện|Tiếng thở dốc hòa cùng tiếng rên rỉ non nớt của cô thiếu nữ ngây thơ bắt đầu nếm trải trái cấm.[p]",
    8514: "Tsubomi「A... a... sướng quá đi mất... Không ngờ làm tình lại tuyệt vời đến thế này...♡」[p]",
    8515: "[舜]「Em thích là tốt rồi... Anh sắp ra rồi đấy」[p]",
    8516: "Tsubomi「Bắn vào trong em đi! Hãy trao trọn vẹn lần đầu tiên này cho em!」[p]",
    8517: "Dẫn chuyện|Tôi thúc sâu một cú dứt khoát, bắn trọn dòng tinh dịch trinh nguyên vào sâu trong lòng Tsubomi.[p]",
    8518: "Tsubomi「A... a... ấm áp quá... Em cảm nhận được dòng tinh dịch của anh rồi...♡」[p]",
    8519: "[舜]「Tsubomi... Giờ em đã chính thức là người phụ nữ của anh rồi đấy」[p]",
    8520: "Tsubomi「Vâng... Từ nay về sau, em thuộc về anh hoàn toàn rồi ạ...♡」[p]",
    8521: "Dẫn chuyện|Vệt máu trinh đỏ thắm hòa quyện cùng dòng tinh dịch trắng ngà lưu lại dấu ấn vĩnh cửu trên ga giường.[p]",
    8522: "Tsubomi「Em hạnh phúc lắm... Cảm ơn anh vì đã nâng niu lần đầu của em nhé...♡」[p]",
    8523: "[舜]「Anh cũng hạnh phúc lắm, Tsubomi à」[p]",
    8524: "Tsubomi「Ưm... Ly rượu Spirytus này mạnh quá... Đầu em quay cuồng hết cả rồi...」[p]",
    8525: "[舜]「Uống từ từ thôi chứ, loại này nồng độ cồn cao lắm đấy」[p]",
    8526: "Tsubomi「Nhưng mà... Uống vào người thấy nóng bừng lên... Thích lắm á...♡」[p]",
    8527: "[舜]「Trông mặt em đỏ ửng hết cả lên rồi kìa, say rồi đúng không?」[p]",
    8528: "Tsubomi「Hì hì... Em không say đâu mà... Chỉ là thấy người rạo rực ngứa ngáy thôi...♡」[p]",
    8529: "Dẫn chuyện|Tsubomi vừa nói vừa tự cởi bỏ từng cúc áo, để lộ làn da ửng hồng quyến rũ.[p]",
    8530: "Tsubomi「Anh [舜] ơi... Nhìn em đi này... Em nóng quá à...♡」[p]",
    8531: "[舜]「Tsubomi... Em biết mình đang làm gì không đấy?」[p]",
    8532: "Tsubomi「Biết chứ... Em đang muốn quyến rũ anh đấy... Không được sao?」[p]",
    8533: "Dẫn chuyện|Em ấy sà vào lòng tôi, đôi bàn tay mềm mại bắt đầu lần mò xuống hạ bộ.[p]",
    8534: "Tsubomi「Oa... Chỗ này của anh cương cứng ngắc rồi kìa... Thích ghê á...♡」[p]",
    8535: "[舜]「Tại em cứ quyến rũ thế này ai mà chịu nổi」[p]",
    8536: "Tsubomi「Thế thì đừng chịu đựng nữa... Mau ăn thịt em đi mà...♡」[p]",
    8537: "Dẫn chuyện|Dưới tác dụng của hơi men nồng nặc, Tsubomi trở nên táo bạo và cuồng nhiệt hơn bao giờ hết.[p]",
    8538: "Tsubomi「A... a... đâm mạnh vào đi anh! Đừng để em phải chờ đợi nữa!」[p]",
    8539: "[舜]「Được thôi, chiều theo ý em hết!」[p]",
    8540: "Dẫn chuyện|Cả hai quấn lấy nhau trong cơn say cuồng loạn, từng cú thúc như thiêu đốt màn đêm.[p]",
    8541: "Tsubomi「Sướng quá đi mất... Rượu ngon cùng với con cu tuyệt hảo của anh... Em lên thiên đường mất rồi...♡」[p]",
    8542: "[舜]「Bắn nhé, Tsubomi!」[p]",
    8543: "Tsubomi「Bắn đi anh! Tưới đẫm cơn say này cho em đi!」[p]",
    8544: "Dẫn chuyện|Dòng tinh dịch cuồng nhiệt phun trào, kết thúc một đêm say đắm đầy hoang dại.[p]",
    8545: "Tsubomi「Hà... hà... Say rượu lẫn say tình... Em chết mê chết mệt anh mất rồi...♡」[p]"
}
