# -*- coding: utf-8 -*-
"""
Part 2 Translations Dictionary - Batch 1 (Lines 9000 - 9250)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P2_DICT_1 = {
    9000: "Giờ đây, Nagi đang ở ngay trước mắt tôi, hoàn toàn ngoan ngoãn phục tùng từng lời tôi nói.[p]",
    9001: "Không hề nghi ngờ, không chút phản kháng. Cứ như thể đó là điều hiển nhiên vậy.[p]",
    9002: "[舜]「……Em sẽ mãi mãi ở bên cạnh anh chứ?」[p]",
    9003: "Nagi「Vâng, em sẽ mãi ở bên anh ạ! ♡ Ưm…! A… a a a!! ♡」[p]",
    9004: "Nagi gật đầu lia lịa không biết bao nhiêu lần.[p]",
    9005: "Trong cử chỉ ấy, chẳng còn sót lại chút bối rối hay sợ hãi nào của ngày xưa nữa.[p]",
    9006: "Hai chúng tôi, đã vĩnh viễn không thể quay trở lại mối quan hệ “bình thường” được nữa rồi.[p]",
    9007: "Bầu không khí bên trong căn phòng khép kín này, vừa là thánh địa của chúng tôi,[p]",
    9008: "Đồng thời, cũng là nhà tù giam cầm mà không ai có thể trốn thoát.[p]",
    9009: "【Nagi - Nô Lệ END: Mật Thất Cuồng Ái】[p]",
    9010: "Sự tĩnh lặng sau giờ đóng cửa bao trùm lấy toàn bộ tiệm massage.[p]",
    9011: "Vừa mới tắm xong, tôi thậm chí còn chẳng buồn lau khô người mà mở toang cánh cửa phòng trị liệu bước vào.[p]",
    9012: "Mục đích chỉ có một. Không phải để dọn dẹp giường nệm, cũng chẳng phải để chuẩn bị cho ngày mai.[p]",
    9013: "Cô Rinko, đang ở ngay đó.[p]",
    9014: "Ngồi trên tấm nệm, chỉ quấn độc một chiếc khăn tắm mỏng manh ngước nhìn tôi.[p]",
    9015: "Rinko「Cô đợi cháu nãy giờ rồi đấy, [舜]-kun♡」[p]",
    9016: "Cô Rinko đã cởi sạch quần áo từ lúc nào, ngồi trên nệm ngước nhìn tôi đắm đuối.[p]",
    9017: "Hương thơm ngọt ngào của sữa tắm thoang thoảng khiến hạ bộ tôi tự động phản ứng ngay lập tức.[p]",
    9018: "Rinko「A, đã cương to lên rồi kìa. Cháu nóng vội ghê chưa♡」[p]",
    9019: "[舜]（Lại dùng cái giọng ngọt xớt nũng nịu đấy áp sát vào người mình rồi…… Đàn bà con gái, sao mà hám dục đến thế không biết）[p]",
    9020: "Rinko「Mau ngồi xuống đây với cô nào…？」[p]",
    9021: "Tsubomi「Gì chứ, mẹ lúc nào cũng ăn gian hết á」[p]",
    9022: "Đúng lúc đó, Tsubomi cũng cởi sạch đồ bước vào phòng.[p]",
    9023: "Tsubomi「Đừng có nhân lúc con đang chuẩn bị mà lén bắt đầu trước chứ」[p]",
    9024: "Rinko「Fufu, mẹ xin lỗi nhé, tại mẹ không kìm lòng nổi…」[p]",
    9025: "[舜]「Đã thèm thuồng thì cứ nói thẳng ra đi, lằng nhằng rắc rối quá」[p]",
    9026: "Không thể nhẫn nhịn thêm được nữa, cô Rinko[p]",
    9027: "Dịu dàng nắm lấy dương vật đang cương cứng cong vút, rồi áp môi ngậm chặt lấy đầu khấc.[p]",
    9028: "Tsubomi「Mẹ ăn gian quá đi♡ Con cũng muốn liếm nữa cơ♡」[p]",
    9029: "Cả hai mẹ con tranh nhau liếm mút dương vật của tôi một cách điên cuồng.[p]",
    9030: "Để đi được đến ngày hôm nay quả là một chặng đường dài……[p]",
    9031: "Dạy dỗ khoái cảm cho cả hai người họ, bóp méo mọi luân thường đạo lý, cuối cùng tôi cũng đã đạt được kết quả này.[p]",
    9032: "Tsubomi「Chụt, mút♡ Này anh, em mút giỏi hơn nhiều rồi đúng không? Nhìn này, em đã ngậm trọn được hết vào miệng rồi nè」[p]",
    9033: "Dù khóe mắt ươn ướt ngấn lệ nhưng Tsubomi vẫn cố gắng ngậm trọn cả cây thịt đầy ắp trong khoang miệng.[p]",
    9034: "Sau khi tốt nghiệp cấp ba và nghỉ việc ở quán massage thư giãn, em ấy đã chuyển sang làm việc tại tiệm của mẹ mình.[p]",
    9035: "Mỗi khi chạm mặt, dù là đang trong giờ mở cửa đón khách, em ấy cũng tìm cách sờ soạng cơ thể tôi để quyến rũ.[p]",
    9036: "[舜]（Đúng là tính dâm đãng thèm muốn này di truyền từ bà mẹ mà ra）[p]",
    9037: "Rinko「Phải tuốt nhẹ phần gốc cho cháu nữa chứ♡」[p]",
    9038: "Đến mức đích thân dạy con gái ruột cách làm cho đàn ông sung sướng, cô Rinko đã hoàn toàn chìm đắm trong dục vọng không lối thoát.[p]",
    9039: "Đó là hình ảnh không thể nào tưởng tượng nổi vào những ngày đầu tôi mới gặp cô ấy… Không, có lẽ đây mới chính là bản chất thực sự của cô ấy chăng.[p]",
    9040: "Đã có một lần tôi cố tình để cho Hayato chứng kiến cảnh tượng của hai mẹ con họ.[p]",
    9041: "[舜]（Cứ tưởng hắn ta sẽ hưng phấn lắm chứ…… Không ngờ, không ngờ hắn lại sốc đến mức suy sụp như vậy）[p]",
    9042: "Sau khi trợn tròn mắt kinh hoàng, hắn ôm đầu la hét rồi lao thẳng ra khỏi tiệm massage.[p]",
    9043: "Kể từ đó, hắn không bao giờ xuất hiện trước mặt tôi hay ở tiệm này nữa. Chẳng biết hắn đã trôi dạt về phương trời nào rồi?[p]",
    9044: "Tsubomi「Nè, anh có đang nghe em nói không đấy? Anh không thấy sướng sao?」[p]",
    9045: "Rinko「Cháu nó đang đê mê tận hưởng đấy con à. Đúng không cháu yêu?」[p]",
    9046: "[舜]「……Đâu có. Chỉ là đang trốn tránh hiện thực một chút thôi」[p]",
    9047: "Giờ đây tôi đang tận hưởng cảm giác thỏa mãn tột cùng nhất trong cả cuộc đời mình.[p]",
    9048: "Được hai mẹ con xinh đẹp phục tùng, thống trị bọn họ, công việc làm ăn thì thuận buồm xuôi gió──[p]",
    9049: "Còn có thứ hạnh phúc nào hơn thế này nữa sao?[p]",
    9050: "[舜]（Nghĩ lại thì… ban đầu mình chỉ định phá hủy hạnh phúc của Nagi thôi mà nhỉ）[p]",
    9051: "Thế mà kết cục lại trở thành thế này đây.[p]",
    9052: "Cuộc đời đúng là chẳng ai có thể đoán trước được điều gì.[p]",
    9053: "Rinko「A… Nóng quá… Sắp bắn rồi sao cháu yêu?」[p]",
    9054: "Tsubomi「Bắn vào trong em đi! Bắn đầy bụng em đi anh!」[p]",
    9055: "Rinko「Không được, phải bắn vào cô chứ!」[p]",
    9056: "[舜]「Cả hai người đừng có ồn ào nữa. Tôi sẽ bắn cho cả hai, lần lượt từng người một」[p]",
    9057: "Hai mẹ con nhìn nhau mỉm cười dâm đãng rồi tiếp tục cúi đầu ngậm chặt lấy dương vật.[p]",
    9058: "Một đêm hoan lạc bất tận của bầy thú dục vọng lại bắt đầu.[p]",
    9059: "【Mẹ Con Rinko & Tsubomi END: Bồn Chứa Tinh Dục Vọng】[p]",
    9060: "Không gian phòng trị liệu nồng nặc mùi tinh dịch và dâm thủy hòa quyện.[p]",
    9061: "Cô Rinko nằm ngửa trên nệm, hai chân banh rộng để lộ vùng kín đẫm nước.[p]",
    9062: "Bên cạnh, Tsubomi đang quỳ gối, chăm chú liếm láp những giọt tinh dịch còn vương trên đùi mẹ mình.[p]",
    9063: "Rinko「Nhìn con gái cô kìa… Dâm đãng chẳng khác nào mẹ nó cả♡」[p]",
    9064: "Tsubomi「Tại vì mùi của anh [舜] ngon quá mà… Mẹ cũng thích lắm còn gì」[p]",
    9065: "[舜]「Được rồi, đến lượt Tsubomi. Lại đây nào」[p]",
    9066: "Tsubomi lập tức bò tới, đưa bờ mông cong vút về phía tôi.[p]",
    9067: "Tsubomi「Cắm vào từ phía sau đi anh… Đâm thật mạnh vào nhé♡」[p]",
    9068: "Dương vật của tôi lại một lần nữa đâm xuyên qua khe thịt ướt sũng của cô thiếu nữ.[p]",
    9069: "Tsubomi「A… a a…! Sướng quá đi mất…! Mẹ ơi, anh ấy đâm sâu lắm nè!」[p]",
    9070: "Rinko rướn người tới, đưa tay xoa nắn đôi gò bồng đảo đang nảy nở của con gái.[p]",
    9071: "Rinko「Cố chịu đựng nhé con gái… Hãy để cho [舜]-kun yêu thương con thật nhiều」[p]",
    9072: "Cảnh tượng hai mẹ con cùng nhau chia sẻ một người đàn ông dâm mỹ đến mức không tưởng.[p]",
    9073: "[舜]「Cả hai người các cô… Đúng là hết thuốc chữa rồi」[p]",
    9074: "Tsubomi「Ưm… Đều là do anh làm cho chúng em biến thành thế này cơ mà…♡」[p]",
    9075: "Rinko「Phải đấy, hãy chịu trách nhiệm với cả hai mẹ con cô đến suốt đời nhé♡」[p]",
    9076: "Từng cú thúc như xé tan màn đêm, đưa cả ba người chìm sâu vào hố sâu hoan lạc.[p]",
    9077: "Tsubomi「A… a… Em ra mất thôi! Mẹ ơi, con sắp lên đỉnh rồi!」[p]",
    9078: "Rinko「Mẹ cũng thế… Nhìn hai người làm mẹ cũng không chịu nổi nữa rồi…!」[p]",
    9079: "[舜]「Bắn nhé…! Nhận lấy toàn bộ đi!」[p]",
    9080: "Dòng tinh dịch nóng hổi phóng thẳng vào sâu trong tử cung của Tsubomi.[p]",
    9081: "Em ấy run rẩy kịch liệt, dâm thủy bắn xối xả ra nệm.[p]",
    9082: "Ngay sau khi rút ra, cô Rinko lập tức áp sát miệng vào nuốt trọn những giọt tinh dịch trào ra từ cửa mình con gái.[p]",
    9083: "Rinko「Ngon quá… Tinh dịch của [舜]-kun lúc nào cũng đậm đà tuyệt hảo…♡」[p]",
    9084: "Tsubomi「Ưm… Mẹ tham lam quá à… Để phần cho con nữa chứ…」[p]",
    9085: "[舜]「Vẫn còn nhiều lắm, đêm nay chúng ta còn dài mà」[p]",
    9086: "Cả hai người phụ nữ nhìn tôi với ánh mắt ngập tràn si mê và khát khao không đáy.[p]",
    9087: "Đây chính là thiên đường tội lỗi mà tôi đã dày công xây dựng.[p]",
    9088: "Một vương quốc nơi dục vọng ngự trị tối cao, không có chỗ cho sự xấu hổ hay hối hận.[p]",
    9089: "【3P Hoan Lạc Cuồng Say: Mẹ Con Naruse】[p]",
    9090: "Đêm đó, tôi đã làm tình với cả hai mẹ con họ cho đến tận khi trời rạng sáng.[p]",
    9091: "Thân thể họ đẫm mồ hôi và tinh dịch, nằm ôm chặt lấy tôi ngủ thiếp đi.[p]",
    9092: "Một cảm giác thỏa mãn và quyền lực tuyệt đối dâng trào trong lồng ngực.[p]",
    9093: "Tôi đã biến gia đình Naruse hoàn toàn trở thành sở hữu của riêng mình.[p]",
    9094: "Không một ai có thể cướp họ khỏi tay tôi được nữa.[p]",
    9095: "Hayato… Cậu có nhìn thấy cảnh này không?[p]",
    9096: "Mẹ và em gái của cậu, giờ đây đang hạnh phúc rên rỉ dưới thân tôi đấy.[p]",
    9097: "Sự trả thù ngọt ngào nhất chính là sự chiếm đoạt hoàn hảo này.[p]",
    9098: "Tôi mỉm cười, vuốt ve mái tóc của hai người phụ nữ bên cạnh rồi nhắm mắt lại.[p]",
    9099: "Một ngày mới đầy khoái lạc lại sắp bắt đầu.[p]",
    9100: "Nagi đang ngồi trên ghế sô pha, đôi mắt mơ màng vì men say của ly rượu Spirytus.[p]",
    9101: "Nagi「Ưm… Shun-chan… Đầu tớ quay cuồng hết cả rồi…」[p]",
    9102: "[舜]「Đã bảo là rượu này mạnh lắm mà cậu cứ cố uống cho hết」[p]",
    9103: "Nagi「Tại tớ tò mò thôi mà… Nhưng mà người nóng ran lên rồi nè…」[p]",
    9104: "Nagi khẽ kéo cổ áo ra, để lộ xương quai xanh trắng nõn ửng hồng.[p]",
    9105: "[舜]（Men rượu ngấm vào rồi… Nhìn Nagi thế này gợi cảm không chịu nổi）[p]",
    9106: "[舜]「Nagi, cậu có biết bây giờ trông cậu quyến rũ thế nào không?」[p]",
    9107: "Nagi「Hả… Quyến rũ ư…? Shun-chan… Đừng nhìn tớ bằng ánh mắt đó mà… Xấu hổ lắm…」[p]",
    9108: "Tôi tiến lại gần, ngồi xuống bên cạnh và khẽ nắm lấy bàn tay mềm mại của Nagi.[p]",
    9109: "Nagi「Tay Shun-chan… Ấm quá…」[p]",
    9110: "[舜]「Người Nagi cũng nóng lắm đấy」[p]",
    9111: "Nagi「Ừm… Tim tớ đập thình thịch luôn nè… Không biết tại rượu hay là tại vì… Ở gần Shun-chan nữa…」[p]",
    9112: "[舜]「Thế Nagi muốn thử xem là vì lý do gì không?」[p]",
    9113: "Nagi「Thử… Thử thế nào cơ…?」[p]",
    9114: "Tôi nhẹ nhàng nâng cằm Nagi lên rồi áp môi mình vào đôi môi ngọt lịm phảng phất men rượu.[p]",
    9115: "Nagi「Ưm…!」[p]",
    9116: "Nagi khẽ giật mình nhưng không hề đẩy tôi ra, trái lại còn vụng về đáp lại nụ hôn.[p]",
    9117: "[舜]「Nagi… Môi cậu ngọt thật đấy」[p]",
    9118: "Nagi「Shun-chan… Hôn nữa đi… Tớ thấy dễ chịu lắm…」[p]",
    9119: "Hơi thở của Nagi ngày càng dồn dập, đôi má đỏ ửng như trái cà chua chín mọng.[p]",
    9120: "Bàn tay tôi bắt đầu luồn vào trong áo, chạm vào bầu ngực căng tròn mềm mại.[p]",
    9121: "Nagi「A… Chỗ đó… Shun-chan… Nhột quá…」[p]",
    9122: "[舜]「Ngực Nagi mềm thật đấy… Đã lớn đến mức này rồi sao」[p]",
    9123: "Nagi「Đừng nói thế mà… Ngại chết đi được… Nhưng mà… Tay cậu ấm lắm…」[p]",
    9124: "Tôi khẽ véo nhẹ đầu nhũ hoa đang cương cứng qua lớp áo lót mỏng.[p]",
    9125: "Nagi「Á…! A… ưm… Cảm giác lạ quá… Bên dưới tớ… Nó cứ rạo rực thế nào ấy…」[p]",
    9126: "[舜]「Bên dưới sao cơ? Để tớ kiểm tra thử xem nhé」[p]",
    9127: "Nagi「Kh-Không được đâu mà… Chỗ đó xấu hổ lắm…」[p]",
    9128: "Dù nói vậy nhưng hai chân Nagi lại khẽ mở ra trong vô thức dưới tác dụng của men rượu.[p]",
    9129: "Bàn tay tôi trượt xuống, chạm vào chiếc quần lót đã ướt đẫm một mảng lớn.[p]",
    9130: "[舜]「Nagi… Ướt nhẹp hết cả rồi này」[p]",
    9131: "Nagi「Không phải đâu… Tại tớ say thôi mà… Trời ơi, xấu hổ quá…」[p]",
    9132: "[舜]「Say rượu mà lại ra nhiều nước thế này sao? Nagi thật là dâm đãng đấy」[p]",
    9133: "Nagi「Đừng trêu tớ mà… Shun-chan… Cậu làm tớ thấy kỳ lạ lắm…」[p]",
    9134: "Tôi khẽ gạt lớp vải sang một bên, dùng ngón tay mơn trớn hạt ngọc nhỏ đang sưng đỏ.[p]",
    9135: "Nagi「A…! A a…! Chỗ đó… Không được chạm vào đâu… Tớ ra mất thôi!」[p]",
    9136: "[舜]「Cứ ra đi, có tớ ở đây rồi mà」[p]",
    9137: "Nagi「A… Shun-chan…! Sướng quá…! Tớ không chịu nổi nữa rồi…!」[p]",
    9138: "Cơ thể Nagi co giật từng hồi, dâm dịch ấm nóng tuôn trào ướt đẫm những ngón tay tôi.[p]",
    9139: "Nagi「Hà… hà… Tớ vừa làm cái gì thế này…」[p]",
    9140: "[舜]「Nagi vừa lên đỉnh đấy. Đáng yêu lắm」[p]",
    9141: "Nagi「Lên đỉnh… Sao lại có cảm giác tuyệt vời đến thế này chứ…」[p]",
    9142: "[舜]「Vẫn còn nhiều thứ tuyệt vời hơn nữa cơ. Nagi có muốn thử không?」[p]",
    9143: "Nagi「Còn nữa sao…? Shun-chan… Hãy dạy cho tớ hết đi…」[p]",
    9144: "Tôi cởi bỏ chiếc quần đùi, để lộ dương vật cương cứng sừng sững trước mắt em ấy.[p]",
    9145: "Nagi「Oa… To quá… Cái này… Có thể đút vào trong người tớ được sao?」[p]",
    9146: "[舜]「Được chứ, Nagi thử chạm vào xem nào」[p]",
    9147: "Nagi rụt rè đưa bàn tay nhỏ nhắn nắm lấy thân nhiệt bổng nóng rực.[p]",
    9148: "Nagi「Nóng quá… Lại còn đập thình thịch nữa… Đây là của Shun-chan sao…」[p]",
    9149: "[舜]「Ừ, nó đang muốn được chui vào bên trong Nagi đấy」[p]",
    9150: "Nagi「Vào trong tớ… Được thôi, nếu là Shun-chan thì tớ sẵn sàng rồi…」[p]",
    9151: "Tôi kê đầu khấc vào cửa mình ướt át của Nagi rồi từ từ nhấn sâu vào.[p]",
    9152: "Nagi「Ưm…! Đau một chút… Nhưng mà… Đầy ắp bên trong rồi…」[p]",
    9153: "[舜]「Khít quá… Nagi thả lỏng ra nào」[p]",
    9154: "Nagi「Hà… phù… Tớ quen rồi… Shun-chan cử động đi…」[p]",
    9155: "Từng cú nhấp chậm rãi ban đầu dần chuyển thành những đợt thúc dồn dập đầy mê đắm.[p]",
    9156: "Nagi「A… a a…! Sâu quá… Chạm vào tận sâu trong bụng tớ rồi…!」[p]",
    9157: "[舜]「Nagi… Bên trong em tuyệt vời lắm…」[p]",
    9158: "Nagi「Shun-chan… Tớ sướng quá… Cơ thể tớ đang tan chảy ra mất rồi…♡」[p]",
    9159: "Tiếng rên rỉ ngọt ngào hòa lẫn tiếng da thịt chạm nhau tạo nên một bản hòa tấu cuồng say.[p]",
    9160: "Nagi「Mạnh nữa lên đi anh… Hãy biến tớ thành của riêng cậu đi!」[p]",
    9161: "[舜]「Nagi đã là của anh từ lâu rồi!」[p]",
    9162: "Nagi「A… a… Tớ sắp ra nữa rồi! Cùng lên đỉnh nhé Shun-chan!」[p]",
    9163: "[舜]「Bắn nhé, Nagi!」[p]",
    9164: "Tôi thúc sâu một cú chí mạng, trút trọn vẹn dòng tinh dịch nồng nàn vào tận cổ tử cung của Nagi.[p]",
    9165: "Nagi「A a a a…!! ♡ Nóng quá… Tinh trùng của Shun-chan đang tràn vào trong tớ rồi…!」[p]",
    9166: "Nagi ôm chặt lấy lưng tôi, cả cơ thể run rẩy đón nhận từng đợt sóng tinh dịch cuộn trào.[p]",
    9167: "Căn phòng ngập tràn men say của rượu và men tình của đôi lứa thanh mai trúc mã.[p]",
    9168: "Nagi「Hà… hà… Hạnh phúc quá… Tớ thuộc về Shun-chan hoàn toàn rồi…」[p]",
    9169: "[舜]「Cảm ơn Nagi nhé, em tuyệt lắm」[p]",
    9170: "Nagi「Lần sau… Lại cho tớ uống rượu rồi làm chuyện này nữa nhé anh…♡」[p]",
    9171: "Nagi nở nụ cười ngây thơ say đắm rồi gục đầu vào ngực tôi ngủ thiếp đi.[p]",
    9172: "Tôi vuốt ve gò má ửng hồng của Nagi, trong lòng dâng trào cảm giác chiếm hữu ngọt ngào.[p]",
    9173: "Hayato à… Người con gái cậu hằng yêu thương, giờ đây đã hoàn toàn là của tôi rồi.[p]",
    9174: "【Nagi x Spirytus: Men Say Tình Đầu】[p]",
    9175: "Nagi khẽ cựa mình, áp sát vào lồng ngực tôi.[p]",
    9176: "Hơi thở của em ấy vẫn còn phảng phất mùi thơm ngọt của rượu.[p]",
    9177: "Một đêm tuyệt vời mà cả hai chúng tôi sẽ không bao giờ có thể quên được.[p]",
    9178: "Tôi kéo tấm chăn mỏng đắp lên người cả hai, ôm chặt Nagi vào lòng.[p]",
    9179: "Tương lai phía trước, Nagi sẽ chỉ thuộc về một mình tôi mà thôi.[p]",
    9180: "Ngủ ngon nhé, Nagi của anh.[p]",
    9181: "Ánh trăng ngoài cửa sổ rọi vào căn phòng tĩnh lặng, chứng giám cho sự gắn kết vĩnh cửu này.[p]",
    9182: "Tất cả mọi rào cản giữa chúng tôi đã hoàn toàn tan biến.[p]",
    9183: "Chỉ còn lại tình yêu và sự chiếm hữu thuần khiết nhất.[p]",
    9184: "Mọi thứ diễn ra đúng như những gì tôi hằng mong đợi.[p]",
    9185: "Kế hoạch trả thù đã biến thành sự chiếm đoạt trọn vẹn nhất.[p]",
    9186: "Và tôi hoàn toàn không hề hối hận về điều đó.[p]",
    9187: "Nagi là của tôi, mãi mãi là như vậy.[p]",
    9188: "Tôi khẽ hôn lên trán Nagi một nụ hôn dịu dàng.[p]",
    9189: "Em ấy mỉm cười trong giấc mơ, ôm tôi chặt hơn một chút.[p]",
    9190: "Một sự bình yên hiếm hoi sau chuỗi ngày toan tính và dục vọng.[p]",
    9191: "Nhưng tôi biết, ngọn lửa ham muốn sẽ không dừng lại ở đây.[p]",
    9192: "Ngày mai, sẽ lại có thêm những trò chơi mới thú vị hơn.[p]",
    9193: "Và Nagi sẽ luôn là bạn đồng hành trung thành nhất của tôi.[p]",
    9194: "Cuộc sống này, cuối cùng cũng trở nên đáng sống rồi.[p]",
    9195: "Tôi nhắm mắt lại, tận hưởng trọn vẹn sự êm ái của màn đêm.[p]",
    9196: "Bên cạnh người con gái tôi yêu thương và chiếm hữu.[p]",
    9197: "Mọi thứ thật hoàn hảo.[p]",
    9198: "Không còn gì để tiếc nuối nữa rồi.[p]",
    9199: "Tạm biệt những ngày tháng u tối của quá khứ.[p]",
    9200: "Từ nay, tôi là người chiến thắng tất cả.[p]",
    9201: "Tsubomi uống cạn ly rượu Spirytus rồi thở hắt ra một hơi nồng nặc mùi cồn.[p]",
    9202: "Tsubomi「Hà… Khét cổ quá đi mất… Nhưng mà sướng thật đấy!」[p]",
    9203: "[舜]「Uống mạnh bạo thế coi chừng sập nguồn đấy nhé」[p]",
    9204: "Tsubomi「Em đâu có yếu đuối như anh nghĩ đâu chứ! Nhìn em đi này!」[p]",
    9205: "Tsubomi đứng phắt dậy, nhưng đôi chân loạng choạng ngã nhào vào lòng tôi.[p]",
    9206: "[舜]「Đấy, thấy chưa, đã bảo là say rồi mà」[p]",
    9207: "Tsubomi「Hì hì… Ngã vào lòng anh thế này thích hơn nhiều…♡」[p]",
    9208: "Tsubomi ngước nhìn tôi, đôi mắt long lanh ngập tràn dục vọng bị kích thích bởi hơi men.[p]",
    9209: "Tsubomi「Anh [舜] ơi… Người em nóng quá à… Cởi đồ giúp em đi…」[p]",
    9210: "[舜]「Tsubomi tự cởi đi chứ, ai lại bắt người khác cởi hộ」[p]",
    9211: "Tsubomi「Tay em bủn rủn hết rồi… Không làm được… Mau giúp em đi mà…♡」[p]",
    9212: "Tôi từ từ cởi bỏ từng cúc áo của Tsubomi, để lộ cơ thể thiếu nữ mơn mởn tràn đầy sức sống.[p]",
    9213: "Tsubomi「Oa… Mát mẻ quá… Nhưng mà bên trong vẫn cứ nóng bừng bừng thế nào ấy…」[p]",
    9214: "[舜]「Để anh giúp em hạ hỏa nhé」[p]",
    9215: "Tsubomi「Hạ hỏa bằng con cu của anh đúng không? Em muốn cái đó cơ♡」[p]",
    9216: "[舜]「Dâm đãng thật đấy, say vào là bộc lộ bản chất ngay」[p]",
    9217: "Tsubomi「Tại vì là ở cùng với anh [舜] nên em mới thế thôi mà… Mau đút vào đi anh!」[p]",
    9218: "Tsubomi tự tay dạng rộng hai chân, để lộ khe dâm đã ướt đẫm dịch nhờn nhầy nhụa.[p]",
    9219: "Tôi đưa dương vật vào vị trí rồi thúc mạnh một cú lút cán.[p]",
    9220: "Tsubomi「A a a a…! ♡ Sâu quá…! Con cu của anh nóng rực như thanh sắt nung vậy…!」[p]",
    9221: "[舜]「Tsubomi bên trong khít và bóp chặt quá… Sướng điên lên được!」[p]",
    9222: "Tsubomi「Em cũng thế… Nhờ có rượu mà cảm giác tăng lên gấp trăm lần luôn á…♡」[p]",
    9223: "Từng cú dập mạnh bạo làm Tsubomi rên rỉ không ngừng, nước dâm bắn tung tóe khắp nơi.[p]",
    9224: "Tsubomi「Mạnh nữa lên anh! Đâm nát tử cung của em đi! Hãy làm em mang thai đi mà!」[p]",
    9225: "[舜]「Em thèm có con với anh đến thế cơ à?」[p]",
    9226: "Tsubomi「Vâng! Em muốn mang thai con của anh [舜]! Em muốn trở thành người phụ nữ của anh trọn đời!」[p]",
    9227: "[舜]「Thế thì nhận lấy này! Anh bắn đây!」[p]",
    9228: "Tôi giữ chặt eo Tsubomi rồi phóng thích toàn bộ lượng tinh dịch tích tụ vào tận sâu bên trong.[p]",
    9229: "Tsubomi「A… a a…! Trào vào rồi…! Tinh dịch của anh nóng quá…! Sướng chết em mất thôi…!」[p]",
    9230: "Cả hai cùng ngã gục xuống sàn trong cơn cực khoái tột đỉnh của thể xác và men say.[p]",
    9231: "Tsubomi「Hà… hà… Rượu Spirytus kết hợp với anh đúng là tuyệt phẩm số một thế gian…♡」[p]",
    9232: "[舜]「Em thỏa mãn rồi chứ, cô bé ngốc?」[p]",
    9233: "Tsubomi「Vẫn chưa đâu… Lát nữa tỉnh rượu lại làm tiếp hiệp nữa nhé anh♡」[p]",
    9234: "Tsubomi ôm chặt lấy cổ tôi, thì thầm những lời âu yếm ngọt ngào bên tai.[p]",
    9235: "Một đêm say sưa đầy cuồng nhiệt của tuổi trẻ.[p]",
    9236: "【Tsubomi x Spirytus: Cuồng Nhiệt Trong Cơn Say】[p]",
    9237: "Tsubomi cười khúc khích, vùi đầu vào ngực tôi làm nũng.[p]",
    9238: "Mùi rượu nồng nàn hòa lẫn với hương thơm thiếu nữ tạo nên một cảm giác thật say đắm.[p]",
    9239: "Tôi xoa đầu em ấy, mỉm cười thỏa mãn.[p]",
    9240: "Tsubomi giờ đây đã hoàn toàn thuộc về tôi, không gì có thể lay chuyển được.[p]",
    9241: "Dù là trên sàn đấu võ hay trên giường ngủ, em ấy cũng đều bị tôi thuần phục tuyệt đối.[p]",
    9242: "Một cảm giác chiến thắng thật trọn vẹn.[p]",
    9243: "Tôi nằm xuống bên cạnh em ấy, nhắm mắt tận hưởng sự bình yên sau cơn hoan lạc.[p]",
    9244: "Tiếng thở đều đặn của Tsubomi vang lên bên tai êm dịu.[p]",
    9245: "Một đêm tuyệt đẹp của hai chúng tôi.[p]",
    9246: "Và tôi biết, những ngày tháng sau này sẽ còn rực rỡ hơn thế nữa.[p]",
    9247: "Tất cả đều nằm trong tầm tay của tôi.[p]",
    9248: "Chúc em ngủ ngon, cô vợ nhỏ dâm đãng của anh.[p]",
    9249: "Hẹn gặp lại em trong những cơn cuồng say tiếp theo.[p]",
    9250: "Màn đêm buông xuống, ôm trọn lấy đôi lứa trong niềm hạnh phúc vô tận.[p]"
}
