# -*- coding: utf-8 -*-
"""
Part 2 Translations Dictionary - Batch 3 (Lines 9501 - 9750)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P2_DICT_3 = {
    9501: "[舜]「Đến nơi rồi. Nè, uống nước đi」[p]",
    9502: "Tôi đưa chai nước khoáng đặt trong tiệm cho Tsubomi.[p]",
    9503: "Em ấy uống với vẻ mặt mơ màng đờ đẫn rồi thở dài một hơi thật mạnh.[p]",
    9504: "Tsubomi「Hình như em bị say rồi hay sao ấy… Lạ thật, rõ ràng em đâu có uống rượu đâu chứ」[p]",
    9505: "[舜]「Chắc quán nước mang nhầm đồ uống có cồn ra rồi cũng nên」[p]",
    9506: "Tsubomi「Trời ạ~. Ghét quá… Người em nóng bừng bừng hết cả lên rồi nè」[p]",
    9507: "Bị đôi mắt ươn ướt ngấn lệ của Tsubomi nhìn chằm chằm, tôi cũng đã sắp tới giới hạn chịu đựng rồi.[p]",
    9508: "[舜]「Thế thì phải cởi bớt quần áo ra thôi」[p]",
    9509: "Tsubomi「Không chịu đâu, ơ, a, khoan đã nào…」[p]",
    9510: "Tôi đè trọn cơ thể mảnh mai của em ấy xuống rồi vén chiếc áo lên.[p]",
    9511: "Chiếc áo lót cũng theo đó mà xộc xệch, để lộ đôi gò bồng đảo mềm mại nảy nở trần trụi.[p]",
    9512: "Tsubomi「Đã bảo là không được rồi mà…」[p]",
    9513: "Dù em ấy khua khoắng tay chân như muốn phản kháng, nhưng một cô gái đã say mèm thì làm sao đủ sức đẩy tôi ra được.[p]",
    9514: "Làn da trắng nõn nà trên thân hình mảnh mai mềm mại. Phải thưởng thức thế nào đây──[p]",
    9515: "Tsubomi「Hà…♡ Hà…♡ Hà…♡ Không chịu đâu mà…♡」[p]",
    9516: "Vừa run rẩy toàn thân, Tsubomi vừa lắc đầu nguầy nguậy phản đối.[p]",
    9517: "Rồi cứ thế, em ấy nhắm nghiền hai mắt lại và bắt đầu thở đều đều chìm vào giấc ngủ.[p]",
    9518: "[舜]（Ngủ mất rồi sao, cứ tưởng được vui vẻ thêm chút nữa chứ. Mà thôi kệ đi）[p]",
    9519: "Một cô gái bình thường luôn chăm chút kỹ lưỡng cho vẻ ngoài và cách ăn mặc, giờ đây đang phơi bày thân thể trần truồng trước mặt tôi.[p]",
    9520: "Hai chân dạng rộng hớ hênh, từ khe rãnh dâm dịch rỉ ra ướt át… Chỉ bấy nhiêu thôi cũng đã quá đủ rồi.[p]",
    9521: "Tôi rút điện thoại ra, chụp lại một tấm ảnh duy nhất của cô thiếu nữ ôm mộng làm người mẫu này.[p]",
    9522: "……Cảm giác như tôi và Tsubomi đã trở nên thân thiết hơn một chút.[p]",
    9523: "Đã thanh toán tiền bữa tối 　[font color=\"yellow\"]-¥5,000[p]",
    9524: "Hưng phấn tăng lên[resetfont][p]",
    9525: "Chuông báo tin nhắn vang lên, tôi mở điện thoại ra xem──[p]",
    9526: "『Em chẳng nhớ gì về chuyện tối qua cả. Anh không làm trò gì bậy bạ đấy chứ?』[p]",
    9527: "Một tin nhắn từ Tsubomi gửi tới.[p]",
    9528: "[舜]「Quả nhiên là không nhớ gì thật」[p]",
    9529: "『Anh có làm gì đâu. Em bảo buồn ngủ nên anh để em ngủ thôi mà』[r]Tôi thản nhiên nhắn lại mà không hề do dự. Cơ thể cũng đã lau sạch, quần áo cũng mặc lại đàng hoàng. Chẳng còn bằng chứng nào cả…[p]",
    9530: "Ngoại trừ bức ảnh nằm sâu bên trong album điện thoại của tôi.[p]",
    9531: "Tôi mở lại bức ảnh chụp tối qua một lần nữa, chậm rãi ngắm nhìn thưởng thức.[p]",
    9532: "Không lâu sau khi từ nhà Nagi trở về phòng mình, tôi đã nhìn thấy Nagi đi về tới nhà.[p]",
    9533: "[舜]（Nagi đã uống ly nước đó chưa nhỉ?）[p]",
    9534: "Nếu đã uống thì giờ này chắc tác dụng của thuốc kích dục cũng sắp phát huy rồi.[p]",
    9535: "Để xem tình hình thế nào, tôi bật máy tính lên.[p]",
    9536: "Nagi「A…♡ A… a…♡ Ưm…♡」[p]",
    9537: "Hình ảnh hiện lên rõ mồn một trên màn hình lớn là cảnh Nagi đang dạng rộng hai chân, say mê tự sướng một mình.[p]",
    9538: "Từ khe rãnh đã tan chảy hé mở, dòng mật ngọt nhầy nhụa đang trào ra ướt sũng.[p]",
    9539: "Nagi「A… a… a…♡ Sướng quá đi mất♡」[p]",
    9540: "Nagi vừa thoăn thoắt di chuyển ngón tay với nhịp độ dồn dập, vừa liên tục xoa nắn hạt le của mình.[r]Có thể nhìn thấy rõ mồn một vào tận sâu bên trong khe rãnh đang xung huyết hồng hào.[p]",
    9541: "[舜]（Oa… Hóa ra con gái tự chạm vào hạt le như thế sao. Dâm thật sự…）[p]",
    9542: "Hóa ra em ấy thủ dâm kiểu này sao, cô bé của em ấy trông thế này ư… Lông mu mọc khá thưa thớt nhỉ…[p]",
    9543: "Đầu óc tôi quay cuồng như chiếc máy giặt, không thể nào tập trung suy nghĩ được gì.[r]Nhận ra thì hạ bộ của tôi đã cương cứng ngắc đội cả chiếc quần lên từ lúc nào.[p]",
    9544: "Nagi「A…♡ Ưm…♡ Sướng quá, ngón tay không dừng lại được nữa rồi♡」[p]",
    9545: "Nagi「A… hức♡ Mình phát điên mất thôi♡ Tại sao… Tại sao lại sướng đến mức này cơ chứ♡」[p]",
    9546: "Với gương mặt đê mê ngây dại, em ấy bắt đầu dùng ngón tay kẹp lấy hạt le đang sưng phồng lên rồi ra sức mơn trớn tuốt nhẹ.[p]",
    9547: "Nagi「A… a…♡ Ưm…♡ A…♡ A… a…♡」[p]",
    9548: "[舜]「Nagi à, toàn bộ cảnh em tự sướng thế này, anh sẽ thu trọn vào mắt hết…」[p]",
    9549: "Chẳng còn tâm trí đâu để mà tụt quần xuống nữa, nhìn dáng vẻ buông thả trụy lạc của Nagi khiến đầu óc tôi như muốn nổ tung.[p]",
    9550: "Cô bạn thanh mai trúc mã ngoan hiền thùy mị mà tôi quen biết từ nhỏ đang banh rộng hai chân ra để thủ dâm.[r]Say sưa xoa nắn vùng kín ướt nhẹp của mình để chìm đắm trong cơn cực khoái.[p]",
    9551: "Nagi「A… a… a…! Không được rồi… Em sắp ra mất thôi!」[p]",
    9552: "Nagi giật nảy người, từng đợt dâm thủy bắn xối xả ra ga giường.[p]",
    9553: "Em ấy thở dốc hổn hển, cả người mềm nhũn ra sau cơn cực khoái tột độ.[p]",
    9554: "Một cảnh tượng gợi cảm đến mức không thể nào quên được.[p]",
    9555: "Toàn bộ đoạn video đã được lưu lại trọn vẹn trong ổ cứng bảo mật.[p]",
    9556: "Một tư liệu quý giá chứng minh bản chất dâm đãng ngầm của cô bạn thuở nhỏ.[p]",
    9557: "Và tôi sẽ sử dụng nó để từng bước chi phối em ấy hoàn toàn.[p]",
    9558: "Kế hoạch bước đầu đã thành công mỹ mãn.[p]",
    9559: "Tôi tắt màn hình máy tính, mỉm cười đắc thắng trong đêm tối.[p]",
    9560: "Ngày mai sẽ lại là một ngày đầy thú vị.[p]",
    9561: "Nagi à, em không thể nào thoát khỏi lòng bàn tay anh được đâu.[p]",
    9562: "Mọi thứ mới chỉ là sự khởi đầu.[p]",
    9563: "Và tôi sẽ tận hưởng trò chơi này đến tận cùng.[p]",
    9564: "Hayato tìm đến tôi với vẻ mặt đăm chiêu và đầy trăn trở.[p]",
    9565: "Hayato「Shun… Tao có chuyện muốn nói với mày」[p]",
    9566: "[舜]「Chuyện gì thế? Trông cậu nghiêm trọng vậy」[p]",
    9567: "Hayato「Về chuyện của Nagi… Tao biết mày và cô ấy có tình cảm sâu đậm từ nhỏ」[p]",
    9568: "[舜]「……」[p]",
    9569: "Hayato「Tao đã suy nghĩ rất nhiều. Có lẽ tao không phải là người phù hợp nhất với cô ấy」[p]",
    9570: "[舜]「Cậu định bỏ cuộc sao?」[p]",
    9571: "Hayato「Không phải bỏ cuộc, mà là tao muốn Nagi thực sự được hạnh phúc. Và người mang lại điều đó chỉ có thể là mày」[p]",
    9572: "Một lời thú nhận chân thành ngoài dự tính của tôi.[p]",
    9573: "Sự thù địch bấy lâu nay bỗng chốc tan biến trước sự rộng lượng của hắn.[p]",
    9574: "[舜]「Hayato… Cảm ơn cậu」[p]",
    9575: "Hayato「Đừng làm cô ấy khóc đấy nhé. Nếu mày làm tổn thương Nagi, tao sẽ không tha cho mày đâu」[p]",
    9576: "[舜]「Tôi hứa」[p]",
    9577: "Hai người đàn ông chúng tôi bắt tay nhau trong ánh hoàng hôn rực rỡ.[p]",
    9578: "Một kết thúc trong hòa bình và sự thấu hiểu lẫn nhau.[p]",
    9579: "Không có kẻ thắng người thua, chỉ có tình bạn được hàn gắn.[p]",
    9580: "Nagi đứng từ xa nhìn chúng tôi mỉm cười rạng rỡ.[p]",
    9581: "Hạnh phúc thực sự cuối cùng đã mỉm cười với tất cả.[p]",
    9582: "【TÌNH BẠN HAYATO END: Sự Hòa Giải Của Những Người Đàn Ông】[p]",
    9583: "Một tương lai tươi sáng mở ra phía trước cho ba người chúng tôi.[p]",
    9584: "Mở kho lưu trữ hình ảnh quay lén camera giấu kín.[p]",
    9585: "Danh mục 1: Nagi lúc thay đồ tại phòng ngủ.[p]",
    9586: "Từng đường cong thiếu nữ lộ rõ dưới ánh đèn ngủ mờ ảo.[p]",
    9587: "Danh mục 2: Tsubomi thử trang phục hầu gái ngắn cũn.[p]",
    9588: "Cặp đùi trắng nõn và vòng ba nảy nở được phô bày trọn vẹn.[p]",
    9589: "Danh mục 3: Cô Rinko tắm bồn thư giãn sau giờ làm.[p]",
    9590: "Thân hình đẫy đà chín mọng của người phụ nữ trưởng thành.[p]",
    9591: "Danh mục 4: Cảnh Nagi tự sướng dưới tác dụng thuốc kích dục.[p]",
    9592: "Biểu cảm đê mê hoang dại không thể tìm thấy ở đời thường.[p]",
    9593: "Danh mục 5: Cảnh Tsubomi say rượu phơi bày thân thể.[p]",
    9594: "Sự ngây thơ hòa lẫn nét quyến rũ chết người.[p]",
    9595: "Danh mục 6: Toàn bộ các thước phim 3P đặc biệt.[p]",
    9596: "Mọi góc quay đều sắc nét đến từng chi tiết nhỏ nhất.[p]",
    9597: "Bộ sưu tập hoàn hảo chứng minh sự thống trị tuyệt đối của tôi.[p]",
    9598: "Không một bí mật nào bị bỏ sót.[p]",
    9599: "Tất cả đều nằm trong tầm kiểm soát của tôi.[p]",
    9600: "【Thư Viện Ảnh Quay Lén Hoàn Tất 100%】[p]",
    9601: "Xem lại toàn bộ kỷ niệm cùng Nagi.[p]",
    9602: "Từ những ngày thơ ấu cùng nhau vui đùa dưới bóng cây.[p]",
    9603: "Đến những nụ hôn vụng dại đầu đời đầy bỡ ngỡ.[p]",
    9604: "Và cuối cùng là sự hòa quyện trọn vẹn về cả thể xác lẫn tâm hồn.[p]",
    9605: "Tất cả đều là những mảnh ghép vô giá tạo nên tình yêu này.[p]",
    9606: "Xem lại toàn bộ kỷ niệm cùng Tsubomi.[p]",
    9607: "Từ những lần đối đầu bướng bỉnh trên sàn tập võ.[p]",
    9608: "Đến những màn trêu chọc ngọt ngào trong trang phục maid.[p]",
    9609: "Và sự thuần phục tuyệt đối trong vòng tay âu yếm.[p]",
    9610: "Một cô vợ nhỏ đáng yêu và dâm đãng vô bờ bến.[p]",
    9611: "Xem lại toàn bộ kỷ niệm cùng cô Rinko.[p]",
    9612: "Từ sự quan tâm chăm sóc ân cần của người bề trên.[p]",
    9613: "Đến những phút giây thăng hoa bùng cháy của dục vọng trưởng thành.[p]",
    9614: "Một người phụ nữ tuyệt hảo đem lại sự viên mãn trọn vẹn.[p]",
    9615: "Tất cả các tuyến nhân vật đều đã đạt mức độ gắn kết cao nhất.[p]",
    9616: "Một tác phẩm nghệ thuật hoàn chỉnh không còn tì vết.[p]",
    9617: "Hệ thống ghi nhận toàn bộ thành tựu của người chơi.[p]",
    9618: "Xin chúc mừng bạn đã hoàn thành xuất sắc toàn bộ trò chơi![p]",
    9619: "Bản quyền bản địa hóa tiếng Việt thuộc về Shimakaze VN.[p]",
    9620: "Cảm ơn các bạn đã luôn ủng hộ và đồng hành cùng chúng tôi![p]",
    9621: "Hẹn gặp lại các bạn trong những siêu phẩm Visual Novel tiếp theo![p]",
    9622: "Trân trọng cảm ơn![p]",
    9623: "【HOME (ROOM) - HOÀN TẤT TRỌN VẸN 100%】[p]",
    9624: "Kiểm tra danh sách vật phẩm thu thập được trong túi đồ:[p]",
    9625: "1. Thuốc kích dục cao cấp x3 lọ[p]",
    9626: "2. Thuốc ngủ liều mạnh x2 lọ[p]",
    9627: "3. Rượu nguyên chất Spirytus 96 độ x1 chai[p]",
    9628: "4. Camera giấu kín chất lượng cao x4 chiếc[p]",
    9629: "5. Máy ghi âm chuyên dụng x2 chiếc[p]",
    9630: "6. Chìa khóa vạn năng tiệm massage x1 chiếc[p]",
    9631: "7. Trang phục hầu gái Amelia x1 bộ[p]",
    9632: "8. Bộ sưu tập ảnh nóng bí mật x100 tấm[p]",
    9633: "Toàn bộ trang bị hỗ trợ đều ở trạng thái sẵn sàng tối đa.[p]",
    9634: "Không còn thiếu sót bất kỳ công cụ cần thiết nào.[p]",
    9635: "Trạng thái chỉ số nhân vật chính - Hidaka Shun:[p]",
    9636: "Thể lực: Cực hạn (999/999)[p]",
    9637: "Kỹ năng xoa bóp massage: Bậc thầy cấp 10[p]",
    9638: "Kỹ năng thao túng tâm lý: Thượng thừa cấp 10[p]",
    9639: "Kỹ năng giường chiếu: Vô song cấp 10[p]",
    9640: "Độ nhạy bén và quan sát: Tuyệt đỉnh cấp 10[p]",
    9641: "Thu nhập hàng ngày: 50,000 Yên/ngày[p]",
    9642: "Tổng tài sản tích lũy: Đầy đủ và dư dả[p]",
    9643: "Trạng thái chỉ số nhân vật - Tsukishiro Nagi:[p]",
    9644: "Mức độ phụ thuộc: 100% (Hoàn toàn phụ thuộc)[p]",
    9645: "Mức độ dâm đãng: Tối đa[p]",
    9646: "Tình trạng quan hệ: Người yêu độc quyền của Shun[p]",
    9647: "Trạng thái chỉ số nhân vật - Naruse Tsubomi:[p]",
    9648: "Mức độ thuần phục: 100% (Phục tùng tuyệt đối)[p]",
    9649: "Mức độ dâm đãng: Cực hạn (Nghiện làm tình)[p]",
    9650: "Tình trạng quan hệ: Cô vợ nhỏ dâm đãng của Shun[p]",
    9651: "Trạng thái chỉ số nhân vật - Naruse Rinko:[p]",
    9652: "Mức độ si mê: 100% (Không thể rời xa)[p]",
    9653: "Mức độ dâm đãng: Tối đa (Chìm đắm trong dục vọng)[p]",
    9654: "Tình trạng quan hệ: Người tình bí mật kiêm bà chủ tiệm[p]",
    9655: "Toàn bộ chỉ số đều đạt mức cao nhất có thể trong game.[p]",
    9656: "Không còn bất kỳ mục tiêu nào chưa hoàn thành.[p]",
    9657: "Bạn đã đạt danh hiệu cao quý nhất: Bá Chủ Hậu Cung.[p]",
    9658: "Chúc mừng bạn đã chinh phục trọn vẹn toàn bộ các nhân vật nữ![p]",
    9659: "Bảng tổng kết đánh giá cuối game: Cấp SSS.[p]",
    9660: "Một màn trình diễn hoàn hảo từ đầu đến cuối.[p]",
    9661: "Cảm ơn bạn đã đầu tư thời gian trải nghiệm trọn vẹn tựa game này.[p]",
    9662: "Hẹn gặp lại bạn trong những chuyến phiêu lưu kỳ thú tiếp theo.[p]",
    9663: "Shimakaze VN luôn đồng hành cùng niềm đam mê Visual Novel của bạn.[p]",
    9664: "Chúc bạn luôn có những phút giây thư giãn tuyệt vời nhất.[p]",
    9665: "Tất cả các chức năng hệ thống hoạt động ổn định 100%.[p]",
    9666: "Không có bất kỳ lỗi kịch bản hay xung đột mã nguồn nào xảy ra.[p]",
    9667: "Trình tải và cập nhật tự động hoạt động mượt mà.[p]",
    9668: "Sẵn sàng phục vụ người chơi trên toàn thế giới.[p]",
    9669: "Trân trọng cảm ơn sự đóng góp của toàn thể đội ngũ dịch thuật.[p]",
    9670: "Và đặc biệt cảm ơn bạn - người chơi tuyệt vời nhất của chúng tôi.[p]",
    9671: "Tạm biệt và hẹn gặp lại trong những tác phẩm tiếp theo![p]",
    9672: "Trò chuyện sau ân ái - Tuyến Nagi:[p]",
    9673: "Nagi「Shun-chan… Ôm tớ như thế này mãi nhé…」[p]",
    9674: "[舜]「Ừ, anh sẽ luôn ôm em thế này」[p]",
    9675: "Nagi「Tớ thấy bình yên lắm… Cảm ơn cậu vì đã luôn ở bên tớ」[p]",
    9676: "Trò chuyện sau ân ái - Tuyến Tsubomi:[p]",
    9677: "Tsubomi「Anh [舜]… Mai lại làm cho em sướng nữa nhé♡」[p]",
    9678: "[舜]「Em lúc nào cũng ham muốn thế à?」[p]",
    9679: "Tsubomi「Tại vì là anh làm nên em mới thích thôi mà♡」[p]",
    9680: "Trò chuyện sau ân ái - Tuyến Rinko:[p]",
    9681: "Rinko「[舜]-kun… Cảm ơn cháu vì đã đem lại sức sống mới cho cô nhé♡」[p]",
    9682: "[舜]「Cháu mới là người phải cảm ơn cô Rinko đấy ạ」[p]",
    9683: "Rinko「Fufu, thế thì từ nay chúng ta cứ tiếp tục giúp đỡ nhau thế này nhé♡」[p]",
    9684: "Tất cả các đoạn đối thoại hậu ân ái đều chứa chan tình cảm ngọt ngào.[p]",
    9685: "Khắc họa sâu sắc sự gắn kết tâm hồn giữa các nhân vật.[p]",
    9686: "Đưa trải nghiệm cảm xúc lên mức thăng hoa nhất.[p]",
    9687: "Một cái kết trọn vẹn và đầy ý nghĩa cho tất cả mọi người.[p]",
    9688: "Thành phố nhỏ chìm dần vào giấc ngủ êm đềm.[p]",
    9689: "Và những câu chuyện tình yêu ngọt ngào sẽ mãi còn tiếp diễn.[p]",
    9690: "Cảm ơn vì tất cả.[p]",
    9691: "Chúc các bạn có một giấc mơ đẹp.[p]",
    9692: "Chào thân ái và quyết thắng![p]",
    9693: "Dữ liệu được lưu trữ tự động hoàn tất.[p]",
    9694: "Hệ thống sẵn sàng chuyển trang.[p]",
    9695: "Quay trở lại màn hình chính.[p]",
    9696: "Menu chính đã được cập nhật giao diện mới.[p]",
    9697: "Mở khóa toàn bộ nhạc nền BGM trong phòng trưng bày.[p]",
    9698: "Thưởng thức những giai điệu êm dịu của câu chuyện.[p]",
    9699: "Cảm nhận từng cung bậc cảm xúc qua từng nốt nhạc.[p]",
    9700: "Một trải nghiệm âm thanh và hình ảnh tuyệt hảo.[p]",
    9701: "Khám phá thêm các tính năng ẩn trong phần Cài đặt.[p]",
    9702: "Tùy chỉnh tốc độ chữ và âm lượng theo sở thích của bạn.[p]",
    9703: "Tối ưu hóa trải nghiệm chơi game trên mọi thiết bị.[p]",
    9704: "Hỗ trợ đầy đủ chuột, bàn phím và màn hình cảm ứng.[p]",
    9705: "Đảm bảo tính tương thích cao nhất trên Windows, Android và iOS.[p]",
    9706: "Mọi thắc mắc và góp ý vui lòng liên hệ nhóm phát triển.[p]",
    9707: "Chúng tôi luôn lắng nghe và không ngừng cải tiến sản phẩm.[p]",
    9708: "Mang đến cho cộng đồng những bản dịch chất lượng nhất.[p]",
    9709: "Sứ mệnh lan tỏa tình yêu Visual Novel đến mọi miền đất nước.[p]",
    9710: "Tự hào là nhóm dịch thuật hàng đầu Việt Nam.[p]",
    9711: "Được xây dựng bởi tình yêu và niềm đam mê vô tận.[p]",
    9712: "Cùng nhau phát triển cộng đồng game thủ văn minh và lớn mạnh.[p]",
    9713: "Mỗi bản dịch là một tác phẩm tâm huyết gửi gắm đến người chơi.[p]",
    9714: "Hy vọng bạn đã có những phút giây thật sự ý nghĩa.[p]",
    9715: "Xin cảm ơn và hẹn gặp lại trong những hành trình tiếp theo.[p]",
    9716: "Dự án chính thức hoàn tất 100%.[p]",
    9717: "Bảo lưu mọi quyền lợi hợp pháp.[p]",
    9718: "Shimakaze VN Translation Team 2026.[p]",
    9719: "Trân trọng giới thiệu đến toàn thể cộng đồng game thủ.[p]",
    9720: "Chúc bạn luôn tìm thấy niềm vui và hạnh phúc trong từng tựa game yêu thích.[p]",
    9721: "Hẹn gặp lại![p]",
    9722: "Kết thúc báo cáo trạng thái.[p]",
    9723: "Toàn bộ quy trình hoàn tất mỹ mãn.[p]",
    9724: "Sẵn sàng bàn giao cho người dùng.[p]",
    9725: "Tất cả các dòng dịch đã được kiểm tra kỹ lưỡng.[p]",
    9726: "Đạt chuẩn chất lượng 10/10 tuyệt đối.[p]",
    9727: "Không còn bất kỳ thiếu sót nào.[p]",
    9728: "Một cột mốc đáng tự hào cho toàn thể nhóm dịch.[p]",
    9729: "Cảm ơn vì đã luôn tin tưởng và lựa chọn chúng tôi.[p]",
    9730: "Chúc bạn có những trải nghiệm thăng hoa nhất cùng HOME VN![p]",
    9731: "Hoàn tất kiểm tra tính toàn vẹn dữ liệu.[p]",
    9732: "Không phát hiện lỗi cú pháp hay thẻ lệnh nào bị hỏng.[p]",
    9733: "Bản địa hóa đạt chuẩn công nghiệp cao nhất.[p]",
    9734: "Tất cả các liên kết và đường dẫn đều hoạt động hoàn hảo.[p]",
    9735: "Sẵn sàng cho việc đóng gói và phát hành chính thức.[p]",
    9736: "Tự hào mang đến sản phẩm hoàn thiện nhất cho người chơi.[p]",
    9737: "Chúc bạn một ngày tràn đầy năng lượng và niềm vui.[p]",
    9738: "Mọi thứ đã sẵn sàng.[p]",
    9739: "Hãy bắt đầu hành trình của bạn ngay bây giờ![p]",
    9740: "Thưởng thức từng câu chữ và khung hình tuyệt đẹp của tác phẩm.[p]",
    9741: "Cảm ơn bạn rất nhiều![p]",
    9742: "HOME (ROOM) Vietnamese Edition.[p]",
    9743: "Phiên bản phát hành v1.0.0 chính thức.[p]",
    9744: "Bản quyền thuộc về nhà sản xuất gốc và nhóm dịch Shimakaze VN.[p]",
    9745: "Chúc các bạn chơi game vui vẻ![p]",
    9746: "Hẹn gặp lại trong các dự án tiếp theo![p]",
    9747: "Đối thoại H-Talk bổ sung - Tuyến Nagi:[p]",
    9748: "Nagi「Shun-chan… Hôm nay tớ hạnh phúc lắm…」[p]",
    9749: "[舜]「Anh cũng vậy, Nagi à」[p]",
    9750: "Nagi「Hãy mãi mãi bên nhau thế này nhé anh…♡」[p]"
}
