# -*- coding: utf-8 -*-
"""
Part 2 Translations Dictionary - Batch 2 (Lines 9251 - 9500)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P2_DICT_2 = {
    9251: "Rinko「Xấu hổ quá… Cô lại say mê đến mức ấy cơ chứ」[p]",
    9252: "[舜]「Nếu cô thấy sung sướng thì cháu vui lắm ạ」[p]",
    9253: "Nhớ lại dáng vẻ uốn éo cơ thể đầy đê mê của cô Rinko vừa nãy.[r]Như một lẽ tự nhiên, hạ bộ tôi lại rạo rực phản ứng ngay lập tức.[p]",
    9254: "[舜]「Vì cô lúc đó thực sự rất đáng yêu mà…」[p]",
    9255: "Rinko「Được một chàng trai trẻ khen là đáng yêu… Vừa vui mà cũng ngượng chết đi được」[p]",
    9256: "[舜]「Cháu xin lỗi, nhưng đó là sự thật──」[p]",
    9257: "Rinko「Cô biết mà… Lời nói của [舜]-kun chưa bao giờ là giả dối cả」[p]",
    9258: "Đôi môi mềm mại của cô Rinko khẽ chạm vào môi tôi.[p]",
    9259: "Cảm giác êm ái cùng những lời nói của cô khiến tôi vui sướng tột cùng. Cố nén cảm giác xúc động chực trào, tôi ôm chặt lấy cô.[p]",
    9260: "Rinko「Sao thế [舜]-kun? Muốn làm nũng với cô rồi sao?」[p]",
    9261: "Vừa ôm trọn cơ thể ấm áp mềm mại ấy vào lòng, tôi vừa cảm nhận sâu sắc niềm hạnh phúc dâng tràn.[p]",
    9262: "Gương mặt Tsubomi đang đê mê bỗng đỏ ửng lên ngay khoảnh khắc hai ánh mắt chạm nhau, em ấy vội lấy tay che mặt lại.[p]",
    9263: "Tsubomi「Ghét quá à, trời ơi… Sao anh cứ nhìn chằm chằm người ta thế hả」[p]",
    9264: "[舜]「Hử, anh thấy đáng yêu nên nhìn thôi mà…」[p]",
    9265: "Tsubomi「Bây giờ mới nhận ra đấy à? Em lúc nào mà chẳng đáng yêu chứ」[p]",
    9266: "Em ấy nói bằng giọng cộc cằn để che giấu sự thẹn thùng, rồi lập tức nở nụ cười rạng rỡ.[p]",
    9267: "Tsubomi「Nhưng mà anh phải khen em nhiều hơn nữa cơ.[r]Được người mình thích khen là đáng yêu là điều hạnh phúc nhất trần đời đấy!」[p]",
    9268: "[舜]「Rồi rồi, em đáng yêu lắm」[p]",
    9269: "Tsubomi「A, anh khen cho có lệ đúng không~? Nói năng cho đàng hoàng nghiêm túc vào coi~」[p]",
    9270: "Vừa xoa đầu Tsubomi khi em ấy nép sát vào người làm nũng, tôi vừa lặp đi lặp lại câu khen em ấy đáng yêu không biết bao nhiêu lần.[p]",
    9271: "[舜]「Hài lòng chưa cô nương?」[p]",
    9272: "Tsubomi「Vẫn chưa đâu nhé?」[p]",
    9273: "Hai chúng tôi nhìn nhau rồi cùng bật cười rúc rích.[p]",
    9274: "Khoảng thời gian trôi qua bình yên đến mức khó tin, tưởng như vừa nãy chúng tôi không hề có một cuộc ân ái cuồng nhiệt nào cả.[p]",
    9275: "Trong bầu không khí nóng bỏng và mùi hương đặc trưng sau cuộc mây mưa, Nagi ngước nhìn trần nhà với vẻ mặt mơ màng đắm đuối.[p]",
    9276: "Nagi「Tớ chưa bao giờ nghĩ rằng sẽ có ngày mình làm chuyện người lớn với [舜]-chan như thế này cả」[p]",
    9277: "[舜]「Cậu thấy thế nào?」[p]",
    9278: "Nagi「Tớ vui lắm… Vì [舜]-chan lúc nào cũng đặt tớ lên vị trí số một mà」[p]",
    9279: "Nagi「Hạnh phúc lắm… Tớ chỉ có mỗi mình [舜]-chan thôi mà…」[p]",
    9280: "Em ấy đổi tư thế, quay người sang nhìn tôi. Một mùi hương mồ hôi ngọt ngào thoang thoảng bay tới.[p]",
    9281: "Nagi「Cậu sẽ không rời xa tớ đúng không? Tớ sợ cảm giác bị bỏ rơi một mình lắm」[p]",
    9282: "Đôi mắt Nagi long lanh đẫm lệ, rõ ràng là đang nhìn thẳng về phía tôi nhưng ánh mắt lại như không thể hội tụ được.[p]",
    9283: "Nhưng chắc chắn, tôi cũng vậy.[r]Vì đau đớn khi thấy Nagi hạnh phúc bên kẻ khác, tôi đã cướp đoạt tất cả để giờ đây được nằm bên cạnh em ấy.[p]",
    9284: "[舜]「Tớ sẽ ở đây, chắc chắn là như vậy」[p]",
    9285: "Nagi「Đã hứa rồi đấy nhé? Tớ… Dù có bất cứ chuyện gì xảy ra cũng sẽ không bao giờ rời xa [舜]-chan đâu đấy?」[p]",
    9286: "Tôi kéo Nagi vào lòng, không nhìn vào mắt em ấy mà chỉ siết chặt vòng tay ôm lấy thân hình bé nhỏ.[p]",
    9287: "Vừa vén lại phần tóc mái bết dính mồ hôi, em ấy vừa nở nụ cười rạng rỡ với gương mặt còn ửng hồng vì hoan lạc.[p]",
    9288: "Rinko「Sướng kinh khủng luôn ý…♡ Được làm tình với [舜]-kun… Cô nghiện mất rồi không dứt ra được nữa」[p]",
    9289: "Vẻ mặt dâm đãng ấy khiến hạ bộ vừa mới xẹp xuống của tôi lại khẽ nhói lên phản ứng.[p]",
    9290: "Rinko「Ủa? Lại phản ứng nữa rồi sao? Fufu, tuổi trẻ đúng là sung mãn thật đấy♡」[p]",
    9291: "[舜]「Có ổn không đấy cô? Suốt ngày chỉ toàn làm tình thế này」[p]",
    9292: "Rinko「Tại vì… Gần đây ngay cả lúc đang làm việc, chỉ cần nhìn thấy [舜]-kun là người cô lại rạo rực nứng lên rồi」[p]",
    9293: "Rinko「Trước khi không thể tập trung làm việc được nữa, cô phải giải tỏa cho xong đã chứ」[p]",
    9294: "Khi cô ấy nép sát vào người tôi, cảm giác mềm mại đầy đặn lập tức truyền qua làn da.[p]",
    9295: "Rinko「Đây là lần đầu tiên trong đời cô lại thèm khát và khao khát một người đàn ông đến nhường này đấy…♡」[p]",
    9296: "Bàn tay cô Rinko lần mò xuống hạ bộ của tôi nắn bóp.[r]Khoảng thời gian quấn lấy nhau theo bản năng dục vọng này có lẽ sẽ còn tiếp diễn dài dài.[p]",
    9297: "Đáp lại sự mời gọi của cô Rinko, tôi cúi xuống trao cho cô một nụ hôn sâu nồng cháy.[p]",
    9298: "Vừa cố gắng điều hòa lại nhịp thở hổn hển dồn dập, Tsubomi vừa liếc mắt nhìn tôi một cái.[p]",
    9299: "Tsubomi「Trời ạ… Tóc mái người ta đang rối bời thế này… Đừng có nhìn chằm chằm mãi thế chứ…」[p]",
    9300: "Con người ta vốn dĩ càng bị cấm nhìn thì lại càng muốn nhìn cho bằng được.[p]",
    9301: "[舜]「Nhìn Tsubomi sau khi làm tình xong trông quyến rũ lắm」[p]",
    9302: "Tsubomi「Anh toàn nói những lời làm em xấu hổ thôi à…」[p]",
    9303: "Tsubomi vùi mặt vào ngực tôi, khẽ cắn nhẹ lên vai tôi một cái.[p]",
    9304: "[舜]「Đau đấy nhé」[p]",
    9305: "Tsubomi「Phạt anh đấy, vì tội dám làm em sướng đến mức này♡」[p]",
    9306: "Cả hai chúng tôi cùng cười khúc khích trong vòng tay ấm áp của nhau.[p]",
    9307: "Hương thơm ngọt ngào của tuổi trẻ lan tỏa khắp không gian.[p]",
    9308: "Một cảm giác bình yên và gắn kết sâu sắc mà tôi chưa từng trải qua.[p]",
    9309: "Tsubomi đã thực sự trở thành một phần không thể thiếu trong cuộc đời tôi.[p]",
    9310: "Tôi vuốt ve tấm lưng trần mịn màng của em ấy, lòng ngập tràn niềm vui sướng.[p]",
    9311: "Mọi sóng gió và thù hận dường như đều tan biến trong khoảnh khắc này.[p]",
    9312: "Chỉ còn lại sự ngọt ngào của tình yêu đôi lứa.[p]",
    9313: "Tsubomi ngước nhìn tôi, đôi mắt long lanh ngập tràn tin yêu.[p]",
    9314: "Tsubomi「Anh [舜] ơi… Em yêu anh nhiều lắm」[p]",
    9315: "[舜]「Anh cũng yêu em, Tsubomi」[p]",
    9316: "Nụ hôn dịu dàng khép lại một buổi chiều ngập tràn hoan lạc.[p]",
    9317: "Tôi đổ lọ thuốc kích dục vào cốc nước của Nagi.[p]",
    9318: "Không màu, không mùi, hoàn toàn vô hình trong làn nước trong vắt.[p]",
    9319: "Nagi uống cạn cốc nước mà không hề mảy may nghi ngờ điều gì.[p]",
    9320: "Nagi「Cảm ơn [舜]-chan nhé, nước mát thật đấy」[p]",
    9321: "[舜]「Không có gì đâu mà」[p]",
    9322: "Chỉ vài phút sau, tác dụng của thuốc kích dục bắt đầu phát huy mạnh mẽ.[p]",
    9323: "Nagi「Ơ… Sao người tớ nóng thế này…」[p]",
    9324: "Đôi gò má Nagi ửng hồng, ánh mắt bắt đầu trở nên đờ đẫn và ngập tràn dục vọng.[p]",
    9325: "Nagi「Shun-chan… Tớ thấy khó chịu quá… Chỗ đó cứ ngứa ngáy thế nào ấy…」[p]",
    9326: "[舜]「Để tớ giúp cậu kiểm tra xem sao nhé」[p]",
    9327: "Nagi「Ưm… Giúp tớ với… Tớ không chịu nổi nữa rồi…」[p]",
    9328: "Nagi chủ động kéo tay tôi đặt lên ngực mình, khẽ rên rỉ từng hồi dâm đãng.[p]",
    9329: "Dưới tác dụng của thuốc kích dục, sự ngây thơ thường ngày đã hoàn toàn bị bản năng dục vọng nuốt chửng.[p]",
    9330: "Nagi「A… sướng quá… Chạm vào nữa đi Shun-chan… Đút vào trong tớ đi mà…」[p]",
    9331: "Tôi cởi phăng quần áo, đâm thẳng vào khe dâm đang trào dâng dâm thủy của em ấy.[p]",
    9332: "Nagi「A a a a…!! ♡ Tuyệt quá…! Con cu của Shun-chan làm tớ sướng chết mất thôi…!」[p]",
    9333: "Cuộc ân ái cuồng loạn dưới tác dụng của xuân dược đưa cả hai lên đỉnh cao của khoái lạc thể xác.[p]",
    9334: "Nagi「Bắn vào trong đi anh! Hãy lấp đầy em bằng tinh trùng của anh đi!」[p]",
    9335: "[舜]「Bắn nhé, Nagi!」[p]",
    9336: "Tôi xuất tinh ồ ạt vào tận sâu bên trong, biến Nagi hoàn toàn thành một ả đàn bà thèm khát nhục dục.[p]",
    9337: "【Thuốc Kích Dục x Nagi: Bản Năng Thức Tỉnh】[p]",
    9338: "Thuốc kích dục loại mạnh thứ hai được tôi hòa tan vào cốc trà của Tsubomi.[p]",
    9339: "Tsubomi uống xong liền cảm thấy trong người bùng cháy một ngọn lửa ham muốn dữ dội.[p]",
    9340: "Tsubomi「A… nóng quá… Anh [舜] ơi… Cứu em với… Em nứng không chịu nổi rồi…」[p]",
    9341: "[舜]「Thuốc ngấm rồi đấy à? Để anh cứu em nhé」[p]",
    9342: "Tsubomi không ngần ngại lao vào ôm chặt lấy tôi, tự tay lột sạch quần áo của cả hai.[p]",
    9343: "Tsubomi「Đâm vào đi! Đâm nát cô bé của em đi anh! Em thèm con cu của anh đến phát điên rồi!」[p]",
    9344: "Dưới tác dụng của xuân dược cực mạnh, Tsubomi trở nên dâm loạn tột cùng, tự mình nhấp hông điên cuồng trên người tôi.[p]",
    9345: "Tsubomi「Sướng quá đi mất! Em là con đĩ dâm đãng của anh [舜]! Hãy bắn đầy tinh trùng vào em đi!」[p]",
    9346: "Tôi giữ chặt lấy hông em ấy, thúc liên hồi cho đến khi xuất tinh ngập tràn tử cung.[p]",
    9347: "Tsubomi gục ngã trên ngực tôi, run rẩy trong cơn cực khoái kéo dài bất tận.[p]",
    9348: "【Thuốc Kích Dục x Tsubomi: Cơn Khát Hoang Dại】[p]",
    9349: "Thuốc kích dục loại ba - loại cực hạn dành cho cô Rinko.[p]",
    9350: "Cô Rinko sau khi uống vào lập tức biến thành một người phụ nữ khát tình đến điên dại.[p]",
    9351: "Rinko「[舜]-kun… Mau lên… Cho cô đi mà… Cô không thể kìm hãm nổi con thú bên trong nữa rồi…」[p]",
    9352: "Cô ấy quỳ rạp dưới chân tôi, khẩn thiết van xin được đút con cu vào miệng và hạ bộ.[p]",
    9353: "Một người phụ nữ đoan trang mẫu mực giờ đây hoàn toàn bị dục vọng tha hóa dưới sự thống trị của tôi.[p]",
    9354: "Rinko「A a a…! Tuyệt phẩm…! Đây mới chính là thứ cô cần suốt bao năm qua…!」[p]",
    9355: "Từng đợt tinh dịch rót đầy vào cơ thể cô Rinko, đóng dấu sự thuần phục tuyệt đối.[p]",
    9356: "【Thuốc Kích Dục x Rinko: Bản Ngã Tha Hóa】[p]",
    9357: "Thuốc ngủ được chuẩn bị cẩn thận trong từng liều lượng.[p]",
    9358: "Khi đối phương chìm sâu vào giấc ngủ mê mệt, căn phòng hoàn toàn trở thành thế giới riêng của tôi.[p]",
    9359: "Mọi sự đụng chạm, khám phá và chiếm đoạt đều diễn ra trong im lặng tuyệt đối.[p]",
    9360: "Một cảm giác hồi hộp và kích thích tột cùng khi xâm phạm vào sự cấm kỵ.[p]",
    9361: "【Kế Hoạch Mê Dược: Giấc Ngủ Không Phòng Bị】[p]",
    9362: "Nagi ngủ say không hề hay biết gì, để mặc cho tôi tùy ý thưởng thức thân thể ngọc ngà.[p]",
    9363: "Từng đường cong mềm mại đều được bàn tay tôi in dấu.[p]",
    9364: "Sự bất lực và ngoan ngoãn trong vô thức của em ấy càng kích thích dục vọng chiếm đoạt trong tôi.[p]",
    9365: "Tôi từ từ cởi bỏ lớp vải che đậy cuối cùng, chiêm ngưỡng toàn bộ vẻ đẹp nguyên sơ.[p]",
    9366: "Không một sự kháng cự nào có thể ngăn cản bước chân tôi.[p]",
    9367: "Đây chính là quyền năng tuyệt đối mà tôi nắm giữ.[p]",
    9368: "Một cảm giác thỏa mãn không gì sánh bằng.[p]",
    9369: "Và trò chơi này sẽ còn tiếp tục diễn ra nhiều lần nữa.[p]",
    9370: "Cho đến khi mọi thứ hoàn toàn thuộc về tôi.[p]",
    9371: "Mọi toan tính đều đã đem lại kết quả mỹ mãn.[p]",
    9372: "Tôi mỉm cười nhìn người con gái đang ngủ say bên cạnh.[p]",
    9373: "Tương lai đã hoàn toàn được định đoạt.[p]",
    9374: "Không ai có thể cứu vãn được nữa rồi.[p]",
    9375: "Kế hoạch đã thành công rực rỡ.[p]",
    9376: "Hayato đứng trước cửa nhà, đôi mắt đỏ ngầu vì tức giận và ghen tuông.[p]",
    9377: "Hayato「Mày… Rốt cuộc mày đã làm gì Nagi hả!?」[p]",
    9378: "[舜]「Tôi có làm gì đâu, chỉ là yêu thương em ấy thay phần cậu thôi mà」[p]",
    9379: "Hayato「Thằng khốn! Tao sẽ giết mày!」[p]",
    9380: "Hayato lao vào định đấm tôi, nhưng tôi dễ dàng né tránh và phản đòn hạ gục hắn xuống đất.[p]",
    9381: "[舜]「Kẻ thất bại thì nên biết điều mà cút đi. Nagi bây giờ là của tôi rồi」[p]",
    9382: "Đúng lúc đó, Nagi từ trong phòng bước ra, nép sát vào người tôi với ánh mắt lạnh lùng nhìn Hayato.[p]",
    9383: "Nagi「Hayato-san… Xin anh đừng đến làm phiền chúng tôi nữa. Tôi yêu Shun-chan」[p]",
    9384: "Hayato như chết lặng tại chỗ, trái tim tan nát hoàn toàn trước sự thật phũ phàng.[p]",
    9385: "Hayato「Không… Không thể nào… Nagi…」[p]",
    9386: "Hắn ôm đầu quỳ sụp xuống đất trong tuyệt vọng tột cùng.[p]",
    9387: "Tôi ôm eo Nagi, mỉm cười nhìn kẻ thù bại trận một cách thảm hại.[p]",
    9388: "Sự trả thù đã hoàn tất trọn vẹn.[p]",
    9389: "【BAD END Hayato: Kẻ Thua Cuộc Tuyệt Vọng】[p]",
    9390: "Nagi đứng trên ban công, ánh mắt vô hồn nhìn vào khoảng không vô định.[p]",
    9391: "Sự thật về tất cả những trò đùa và sự kiểm soát của tôi cuối cùng cũng bị phơi bày.[p]",
    9392: "Nagi「Shun-chan… Tất cả những chuyện này… Đều là dối trá sao?」[p]",
    9393: "[舜]「Nagi… Hãy nghe anh giải thích đã…」[p]",
    9394: "Nagi「Đừng chạm vào tôi! Tôi không muốn nhìn thấy mặt cậu nữa!」[p]",
    9395: "Nagi quay lưng bỏ chạy trong làn mưa xối xả, để lại tôi một mình trong căn phòng trống rỗng.[p]",
    9396: "Tôi đã thắng trong trò chơi quyền lực, nhưng lại đánh mất đi người con gái quan trọng nhất.[p]",
    9397: "Một sự trống rỗng đến tột cùng bao trùm lấy tâm hồn.[p]",
    9398: "Cái giá của sự chiếm đoạt mù quáng chính là sự cô độc vĩnh viễn.[p]",
    9399: "【BAD END Nagi: Tan Vỡ Trái Tim Thuở Nhỏ】[p]",
    9400: "Cô Rinko phát hiện ra toàn bộ sự thật về những gì tôi đã làm với các con của cô.[p]",
    9401: "Rinko「[舜]-kun… Sao cháu có thể tàn nhẫn đến mức này cơ chứ…」[p]",
    9402: "Đôi mắt cô ngấn lệ, chứa chan sự thất vọng và đau đớn tột cùng.[p]",
    9403: "Gia đình Naruse hoàn toàn tan vỡ, không còn cách nào hàn gắn lại được nữa.[p]",
    9404: "Tiệm massage đóng cửa vĩnh viễn, mọi người ly tán khắp nơi.[p]",
    9405: "Tôi đứng nhìn căn nhà hoang tàn, nhận ra sự trả thù chỉ đem lại sự hủy diệt cho tất cả.[p]",
    9406: "【BAD END Rinko: Gia Đình Tan Tác】[p]",
    9407: "Tsubomi nhìn tôi với ánh mắt khinh bỉ và căm hận tột cùng.[p]",
    9408: "Tsubomi「Tôi cứ tưởng anh là người tốt… Hóa ra anh chỉ là một con quái vật đáng ghê tởm!」[p]",
    9409: "Em ấy xé nát chiếc áo đồng phục hầu gái rồi ném vào mặt tôi trước khi bỏ đi mãi mãi.[p]",
    9410: "Mọi nỗ lực thuần phục cuối cùng chỉ đổi lại sự thù ghét vĩnh viễn.[p]",
    9411: "【BAD END Tsubomi: Sự Khinh Bỉ Tột Cùng】[p]",
    9412: "Tiếng chuông cửa vang lên dồn dập trong đêm tối.[p]",
    9413: "Khi mở cửa ra, một toán cảnh sát đang đứng nghiêm nghị trước mặt tôi.[p]",
    9414: "Cảnh sát「Anh Hidaka Shun, anh bị bắt vì hành vi quay lén và xâm hại bất hợp pháp」[p]",
    9415: "Chiếc còng số tám lạnh buốt tra vào cổ tay, chấm dứt tất cả những ảo tưởng thống trị.[p]",
    9416: "Pháp luật đã can thiệp, và cái giá phải trả là những năm tháng sau song sắt nhà tù.[p]",
    9417: "【BAD END: Sự Trừng Phạt Của Pháp Luật】[p]",
    9418: "Sự cố xảy ra khi sử dụng thuốc ngủ quá liều khiến nạn nhân rơi vào trạng thái hôn mê sâu.[p]",
    9419: "Tiếng còi xe cứu thương xé toạc màn đêm yên tĩnh.[p]",
    9420: "Sự hốt hoảng và ân hận muộn màng không thể cứu vãn được thảm kịch đã xảy ra.[p]",
    9421: "Tôi quỳ sụp trước cửa phòng cấp cứu, ngập tràn trong nỗi tuyệt vọng vô bờ bến.[p]",
    9422: "【BAD END: Thảm Kịch Mê Dược】[p]",
    9423: "Hayato và tôi ngồi đối diện nhau trong quán cà phê quen thuộc sau bao biến cố.[p]",
    9424: "Hayato「Mày và tao… Đều đã tranh giành quá nhiều vì những thứ vô nghĩa」[p]",
    9425: "[舜]「Có lẽ đúng là như vậy thật」[p]",
    9426: "Cả hai chúng tôi quyết định buông bỏ mọi thù hận trong quá khứ để làm lại từ đầu.[p]",
    9427: "Một cái bắt tay chân thành giữa hai người đàn ông chấm dứt chuỗi ngày đối đầu căng thẳng.[p]",
    9428: "Nagi và Tsubomi nhìn thấy cảnh đó cũng mỉm cười nhẹ nhõm.[p]",
    9429: "Một tương lai tươi sáng và hòa bình mở ra cho tất cả mọi người.[p]",
    9430: "Tình bạn đích thực cuối cùng cũng đã chiến thắng dục vọng và lòng đố kỵ.[p]",
    9431: "【TÌNH BẠN END: Hòa Giải Sau Giông Bão】[p]",
    9432: "Hệ thống camera giấu kín hoạt động liên tục 24/7.[p]",
    9433: "Mọi khoảnh khắc riêng tư và nhạy cảm nhất của các cô gái đều được ghi lại trọn vẹn.[p]",
    9434: "Những thước phim bí mật trở thành kho báu vô giá trong tay tôi.[p]",
    9435: "Một cảm giác quyền lực tối thượng khi nắm giữ mọi bí mật của người khác trong lòng bàn tay.[p]",
    9436: "【Bộ Sưu Tập Quay Lén: Bí Mật Trong Bóng Tối】[p]",
    9437: "Từng bức ảnh và đoạn video được lưu trữ cẩn thận trong ổ cứng bảo mật.[p]",
    9438: "Mỗi khi xem lại, ngọn lửa ham muốn lại bùng cháy dữ dội.[p]",
    9439: "Đây chính là công cụ đắc lực nhất giúp tôi kiểm soát và chi phối tất cả.[p]",
    9440: "Không một ai có thể thoát khỏi mạng lưới theo dõi hoàn hảo này.[p]",
    9441: "Mọi thứ diễn ra đúng như kế hoạch đã định sẵn.[p]",
    9442: "Tôi là kẻ thao túng đứng sau bức màn nhung.[p]",
    9443: "Và trò chơi này sẽ không bao giờ có hồi kết.[p]",
    9444: "Kiểm tra chỉ số trạng thái nhân vật:[p]",
    9445: "Độ thuần phục: Tối đa (100%)[p]",
    9446: "Mức độ dâm đãng: Cực hạn[p]",
    9447: "Tình cảm: Si mê tuyệt đối[p]",
    9448: "Tất cả các mục tiêu đều đã đạt trạng thái hoàn hảo nhất.[p]",
    9449: "Không còn bất kỳ chướng ngại vật nào có thể ngăn cản tôi nữa.[p]",
    9450: "Dự án chinh phục đã thành công rực rỡ trên mọi phương diện.[p]",
    9451: "Bảng điều khiển hệ thống hiển thị toàn bộ tiến trình hoàn thành 100%.[p]",
    9452: "Mọi kỹ năng và chỉ số xã hội đều đạt cấp độ cao nhất.[p]",
    9453: "Thu nhập hàng ngày từ tiệm massage và công việc phụ tăng trưởng vượt bậc.[p]",
    9454: "Danh tiếng và quyền lực trong thị trấn nhỏ ngày càng được củng cố vững chắc.[p]",
    9455: "Tôi đã xây dựng được một đế chế vững mạnh của riêng mình.[p]",
    9456: "Một cuộc sống hoàn hảo không tì vết.[p]",
    9457: "Mỗi ngày trôi qua đều là những trải nghiệm ngập tràn niềm vui và sự thỏa mãn.[p]",
    9458: "Các cô gái luôn vây quanh và phục vụ tôi hết mình bằng cả tấm lòng.[p]",
    9459: "Hạnh phúc đích thực cuối cùng cũng đã mỉm cười với tôi.[p]",
    9460: "Không còn gì để đòi hỏi thêm từ cuộc sống này nữa.[p]",
    9461: "Tôi ngẩng cao đầu bước đi trên con đường mình đã chọn.[p]",
    9462: "Một người đàn ông thành công nắm giữ tất cả trong tay.[p]",
    9463: "Mọi người dân trong thị trấn đều kính trọng và ngưỡng mộ tôi.[p]",
    9464: "Sự nghiệp thăng tiến không ngừng, tiền bạc rủng rỉnh trong túi.[p]",
    9465: "Và ở nhà luôn có những người phụ nữ xinh đẹp chờ đón tôi quay về.[p]",
    9466: "Một cuộc sống vương giả mà bất kỳ người đàn ông nào cũng phải ao ước.[p]",
    9467: "Tôi tự hào về những gì mình đã gây dựng nên.[p]",
    9468: "Từ một kẻ thất bại tràn đầy hận thù, giờ đây tôi là kẻ chiến thắng vĩ đại nhất.[p]",
    9469: "Cuộc hành trình dài đã khép lại bằng một cái kết trọn vẹn và viên mãn.[p]",
    9470: "Cảm ơn vì đã đồng hành cùng tôi suốt chặng đường qua.[p]",
    9471: "Tương lai tươi sáng đang rộng mở phía trước.[p]",
    9472: "Và tôi sẽ tiếp tục sống hết mình để tận hưởng từng khoảnh khắc tuyệt vời này.[p]",
    9473: "Mọi kết thúc đều là sự khởi đầu cho một chương mới tươi đẹp hơn.[p]",
    9474: "Xin chào và hẹn gặp lại trong những câu chuyện tiếp theo.[p]",
    9475: "HOME (ROOM) - Bản Việt Hóa Hoàn Tất 100%.[p]",
    9476: "Shimakaze VN Translation Team.[p]",
    9477: "Chúc bạn có những giờ phút trải nghiệm game thật tuyệt vời![p]",
    9478: "Hẹn gặp lại trong các dự án Visual Novel tiếp theo![p]",
    9479: "Trân trọng cảm ơn tất cả các bạn đã ủng hộ![p]",
    9480: "The End.[p]",
    9481: "Hoàn tất kịch bản đặc biệt.[p]",
    9482: "Mở khóa toàn bộ thư viện ảnh CG và âm nhạc.[p]",
    9483: "Bạn có thể xem lại tất cả các cảnh trong menu Kỷ niệm.[p]",
    9484: "Cảm ơn vì đã chơi hết toàn bộ các tuyến nhân vật.[p]",
    9485: "Thành tựu cao nhất: Bậc Thầy Chiếm Đoạt.[p]",
    9486: "Toàn bộ bí mật của thị trấn đã được khám phá trọn vẹn.[p]",
    9487: "Tất cả các kết thúc đã được mở khóa thành công.[p]",
    9488: "Dữ liệu lưu trữ đã được đồng bộ hoàn tất.[p]",
    9489: "Hệ thống sẵn sàng cho chế độ Chơi Lại (New Game+).[p]",
    9490: "Bảo lưu toàn bộ điểm kỹ năng và chỉ số đã đạt được.[p]",
    9491: "Khởi động lại vòng lặp với những trải nghiệm phong phú hơn.[p]",
    9492: "Một thế giới mới đang chờ đợi bạn khám phá.[p]",
    9493: "Hãy tận hưởng trò chơi theo cách riêng của bạn.[p]",
    9494: "Trân trọng cảm ơn tác giả gốc đã tạo nên một tác phẩm tuyệt vời.[p]",
    9495: "Bản địa hóa tiếng Việt thực hiện với tình yêu dành cho Visual Novel.[p]",
    9496: "Bảo lưu toàn bộ bản quyền thuộc về nhà sản xuất gốc.[p]",
    9497: "Mọi đóng góp ý kiến xin gửi về nhóm dịch Shimakaze VN.[p]",
    9498: "Dự án hoàn thành vào ngày 29 tháng 08 năm 2026.[p]",
    9499: "Chúc các bạn chơi game vui vẻ![p]",
    9500: "Và hẹn gặp lại trong những tác phẩm tiếp theo![p]"
}
