# -*- coding: utf-8 -*-
"""
Part 2 Translations Dictionary - Batch 4 (Lines 9751 - 9922)
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

P2_DICT_4 = {
    9751: "[font color=\"yellow\"]Dũng cảm tăng lên[r]Căng thẳng giảm xuống[resetfont][p]",
    9752: "[舜]「Thưa quý khách, hành động quá khích này của quý khách đang gây cản trở kinh doanh đấy ạ……」[p]",
    9753: "Khách nam「Mày là cái thá gì hả thằng ranh! Chỉ là nhân viên quèn mà dám lên giọng dạy đời tao à!」[p]",
    9754: "[舜]「Ư…… Việc này sẽ gây phiền toái cho các khách hàng khác nữa…… nên là……」[p]",
    9755: "Đúng lúc tôi đang lúng túng nghẹn lời,[r]người quản lý vừa kịp thời chạy tới, nắm bắt tình hình và lập tức chỉ thị báo cảnh sát.[p]",
    9756: "Gã khách đành miễn cưỡng nghe theo và bị áp giải ra khỏi quán.[p]",
    9757: "[chara_mod name=\"kyara_tubomi_sabun\" cross=\"false\" time=\"500\" storage=\"chara/181/ADV_tubomi_00_03c.gif\"]Tsubomi「Hà…… Sợ chết đi được…… Loại người như thế, em không bao giờ muốn thấy quay lại đây nữa đâu」[p]",
    9758: "[舜]（……Mình có hơi hèn nhát một chút thì phải. Giá như mình dũng cảm hơn……）[p]",
    9759: "[font color=\"yellow\"]Căng thẳng tăng lên[resetfont][p]",
    9760: "[舜]「…Tạm thời cứ theo dõi tình hình xem sao đã. Có khi một lát nữa sẽ êm xuôi thôi」[p]",
    9761: "Tsubomi「N-Nhưng mà…… nguy hiểm lắm đấy……」[p]",
    9762: "Rốt cuộc chẳng có ai dám bước vào phòng 3, một lát sau trong quán vang lên tiếng quát tháo và tiếng thủy tinh vỡ toang.[p]",
    9763: "…Vài phút sau, người quản lý đến trễ và buộc phải gọi cảnh sát can thiệp.[p]",
    9764: "[chara_mod name=\"kyara_tubomi_sabun\" cross=\"false\" time=\"500\" storage=\"chara/181/ADV_tubomi_00_03c.gif\"]Tsubomi「May quá… Cứ nghĩ đến chuyện nếu chủ quán không tới kịp là em lại thấy rợn hết cả người…」[p]",
    9765: "[舜]（Có vẻ mình hơi thiếu bản lĩnh rồi… Nhưng biết làm sao được chứ）[p]",
    9766: "[font color=\"yellow\"]Căng thẳng tăng lên[resetfont][p]",
    9767: "[舜]「Oáp~ Quả nhiên là lúc rạng sáng buồn ngủ thật đấy… Thôi thì cứ bắt đầu bằng việc quét dọn quét tước vậy」[p]",
    9768: "[舜]「Ủa, có chuyện gì thế cô Rinko?」[p]",
    9769: "Rinko「A… [舜]-kun. Thật ra là cô lỡ đặt nhầm số lượng hàng mất rồi….[r]Người ta vừa giao tới tận 10 thùng các tông to đùng lận」[p]",
    9770: "[舜]「Thế này thì bít kín hết lối vào của tiệm rồi còn gì」[p]",
    9771: "[chara_mod name=\"kyara_rinko_sabun\" cross=\"false\" time=\"500\" storage=\"chara/180/ADV_rinko_00_06c.gif\"]Rinko「Trời ạ… Cô thật là đãng trí quá. Đống này nặng thế này di chuyển cũng mệt lắm, phải làm sao bây giờ đây……」[p]",
    9772: "[font color=\"yellow\"]Cảm giác như “Sức mạnh” của bạn đang được thử thách.[resetfont]",
    9773: "[舜]「Không sao đâu ạ, để cháu làm cho. Bê vào kho chứa phía sau đúng không cô?」[p]",
    9774: "[chara_mod name=\"kyara_rinko_sabun\" cross=\"false\" time=\"500\" storage=\"chara/180/ADV_rinko_00_00c.gif\"]Rinko「Ơ? Nặng thế này mà [舜]-kun bê nổi sao?」[p]",
    9775: "[舜]「Vâng, cứ bê từng thùng một thì không thành vấn đề đâu ạ」[p]",
    9776: "[chara_mod name=\"kyara_rinko_sabun\" cross=\"false\" time=\"500\" storage=\"chara/180/ADV_rinko_00_04c.gif\"]Rinko「……Cảm ơn cháu nhé, [舜]-kun. Con trai có khác, trông cậy được thật đấy.[r]Cứ làm nũng cháu thế này cô ngại quá」[p]",
    9777: "[font color=\"yellow\"]Chu đáo tăng lên[r]Căng thẳng giảm xuống[resetfont][p]",
    9778: "[舜]「Không sao đâu ạ, để cháu lo cho. Chỉ cần chuyển vào kho phía sau là được đúng không cô?」[p]",
    9779: "[舜]（Ư……! Nặng hơn mình tưởng nhiều quá……! Kh-Không xong rồi…… Nhấc không nổi）[p]",
    9780: "[chara_mod name=\"kyara_rinko_sabun\" cross=\"false\" time=\"500\" storage=\"chara/180/ADV_rinko_00_02c.gif\"]Rinko「[舜]-kun, đừng cố quá cháu ơi. Để cô sang cửa hàng bên cạnh mượn chiếc xe đẩy nhé」[p]",
    9781: "[舜]（Ư ư…… Xấu hổ thật đấy. Giá như mình chịu khó rèn luyện thể lực nhiều hơn）[p]",
    9782: "[font color=\"yellow\"]Căng thẳng tăng lên[resetfont][p]",
    9783: "[chara_mod name=\"kyara_rinko_sabun\" cross=\"false\" time=\"500\" storage=\"chara/180/ADV_rinko_00_00c.gif\"]Rinko「[舜]-kun, cô sang tiệm bên cạnh mượn xe đẩy, trong lúc đó cháu trông tiệm giúp cô một lát được không?」[p]",
    9784: "[舜]「Cháu hiểu rồi ạ. Cứ giao cho cháu」[p]",
    9785: "[舜]（Mà thôi, sức mình cũng chẳng nhấc nổi. Thế này là giải pháp êm đẹp nhất rồi）[p]",
    9786: "[font color=\"yellow\"]Căng thẳng tăng lên[resetfont][p]",
    9787: "[舜]（Được rồi. Hôm nay cũng phải xốc lại tinh thần làm tốt công việc dọn dẹp mới được）[p]",
    9788: "[舜]（Hử? Nagi đang mặt đỏ bừng, vừa ôm thứ gì đó vừa hớt hải chạy lại đây kìa）[p]",
    9789: "Nagi「[舜]-chan……! Ph-Phải làm sao bây giờ, tớ lỡ tay làm rơi vỡ máy bệnh án điện tử rồi![r]Mới vừa nãy vẫn còn chạy bình thường cơ mà…… Trời ơi~ Sao tôi lại ngốc thế này chứ!」[p]",
    9790: "Chiếc máy tính bảng cầm trên tay màn hình tối đen như mực. Với vẻ mặt sắp khóc đến nơi, Nagi cuống cuồng cầu cứu tôi.[p]",
    9791: "[舜]「N-Bình tĩnh lại đã nào. Hít thở sâu vào…… Trước tiên đưa đây cho tớ xem tình hình thế nào đã」[p]",
    9792: "[font color=\"yellow\"]Cảm giác như “Trí tuệ” của bạn đang được thử thách.[resetfont]",
    9793: "[舜]「Đưa tớ mượn một chút nào. Đâu xem nào… A, nó hiện mã lỗi này thôi. Trường hợp này thì… Xong rồi」[p]",
    9794: "[舜]「Nhìn này, khởi động lại được rồi nhé. Dữ liệu hình như vẫn còn nguyên vẹn đấy」[p]",
    9795: "[chara_mod name=\"kyara_nagi_sabun2\" cross=\"false\" time=\"500\" storage=\"chara/179/ADV_nagi_01_01c.gif\"]Nagi「A… Thật kìa. May quá đi mất… [舜]-chan, thực sự cảm ơn cậu nhiều lắm!」[p]",
    9796: "Nagi「[舜]-chan từ xưa đã thông minh lắm rồi mà. Quả nhiên là đáng tin cậy ghê……」[p]",
    9797: "[font color=\"yellow\"]Giao tiếp tăng lên[r]Căng thẳng giảm xuống[resetfont][p]",
    9798: "[舜]「Đưa tớ mượn xem thử nhé. …Ưm, tạm thời cứ thử khởi động lại xem sao đã……」[p]",
    9799: "[舜]「…Không được rồi. Màn hình vẫn tối thui một màu đen」[p]",
    9800: "[chara_mod name=\"kyara_nagi_sabun2\" cross=\"false\" time=\"500\" storage=\"chara/179/ADV_nagi_01_00c.gif\"]Nagi「V-Vậy sao…. Để tớ đi hỏi ý kiến tiền bối xem sao nhé! Cảm ơn cậu nhiều!」[p]",
    9801: "[舜]（Chịu thôi… Đồ điện tử hỏng hóc đâu phải lúc nào cũng sửa được ngay đâu）[p]",
    9802: "[font color=\"yellow\"]Căng thẳng tăng lên[resetfont][p]",
    9803: "[舜]「Nagi cứ đi báo với cấp trên đi. Đừng tự trách mình nữa」[p]",
    9804: "Nagi「Ừm… Tớ biết rồi. Tớ đi ngay đây」[p]",
    9805: "Nhìn bóng lưng lo lắng của Nagi, tôi thầm nhủ phải cố gắng học hỏi thêm nhiều kiến thức hơn nữa.[p]",
    9806: "Công việc lau dọn tại bệnh viện tiếp tục diễn ra suôn sẻ.[p]",
    9807: "Tiếng bước chân gấp gáp của các bác sĩ và y tá vang vọng khắp hành lang.[p]",
    9808: "Tôi cẩn thận lau từng ô kính cửa sổ, đảm bảo không gian luôn sạch sẽ tinh tươm.[p]",
    9809: "Một ngày làm việc chăm chỉ trôi qua thật nhanh chóng.[p]",
    9810: "Đã nhận tiền lương làm thêm hôm nay 　[font color=\"yellow\"]+¥8,000[p]",
    9811: "Độ siêng năng tăng lên[resetfont][p]",
    9812: "Rời khỏi bệnh viện, tôi rảo bước trở về căn nhà thân thuộc.[p]",
    9813: "Gió chiều mùa thu thổi nhẹ qua những tán cây bên đường mang lại cảm giác dễ chịu.[p]",
    9814: "Kế hoạch của tôi đang từng bước tiến triển thuận lợi.[p]",
    9815: "Tối nay sẽ là một buổi tối đầy hứa hẹn.[p]",
    9816: "Tôi mở điện thoại kiểm tra lại lịch trình ngày mai.[p]",
    9817: "Mọi thứ đều đã được chuẩn bị chu đáo.[p]",
    9818: "Không có chỗ cho bất kỳ sai sót nào.[p]",
    9819: "Về tới nhà, tôi bật máy tính kiểm tra lại các đoạn phim theo dõi.[p]",
    9820: "Những hình ảnh tuyệt đẹp lại được bổ sung vào bộ sưu tập.[p]",
    9821: "Một nụ cười đắc thắng khẽ nở trên môi.[p]",
    9822: "Tôi bắt đầu lên kế hoạch cho những bước tiếp theo.[p]",
    9823: "Trò chơi này ngày càng trở nên hấp dẫn hơn bao giờ hết.[p]",
    9824: "Bắt đầu ca làm việc buổi tối tại tiệm massage Naruse.[p]",
    9825: "Cô Rinko mỉm cười chào đón tôi bằng ánh mắt dịu dàng.[p]",
    9826: "Rinko「Hôm nay cũng nhờ cháu nhé, [舜]-kun」[p]",
    9827: "[舜]「Vâng, cháu sẽ cố gắng hết sức ạ」[p]",
    9828: "Khách hàng lần lượt ra vào, công việc diễn ra tấp nập.[p]",
    9829: "Tay nghề massage của tôi ngày càng trở nên điêu luyện và thuần thục.[p]",
    9830: "Các khách hàng đều khen ngợi hết lời về kỹ thuật xoa bóp.[p]",
    9831: "Doanh thu của tiệm ngày càng tăng trưởng mạnh mẽ.[p]",
    9832: "Cô Rinko nhìn tôi với ánh mắt đầy tự hào và biết ơn.[p]",
    9833: "Rinko「Có [舜]-kun ở đây giúp đỡ, tiệm của cô phát đạt hơn hẳn」[p]",
    9834: "[舜]「Đều nhờ cô Rinko chỉ dẫn tận tình cho cháu đấy ạ」[p]",
    9835: "Sau giờ làm việc, cô Rinko thưởng thêm cho tôi một khoản tiền nhỏ.[p]",
    9836: "Đã nhận tiền thưởng 　[font color=\"yellow\"]+¥10,000[p]",
    9837: "Kỹ năng xoa bóp tăng lên[resetfont][p]",
    9838: "Tsubomi từ trường học trở về, ghé vào tiệm với bộ đồng phục nữ sinh đáng yêu.[p]",
    9839: "Tsubomi「Anh [舜] hôm nay làm việc chăm chỉ ghê nhỉ」[p]",
    9840: "[舜]「Đương nhiên rồi, đâu có lười biếng như ai đó」[p]",
    9841: "Tsubomi「Xì, em cũng học hành vất vả lắm chứ bộ!」[p]",
    9842: "Hai chúng tôi lại trêu chọc nhau rôm rả như thường lệ.[p]",
    9843: "Không khí gia đình ấm cúng tràn ngập căn nhà nhỏ.[p]",
    9844: "Nhưng ẩn sâu dưới vẻ bình yên ấy là những bí mật đen tối đang dần nảy nở.[p]",
    9845: "Và tôi chính là người điều khiển tất cả.[p]",
    9846: "Đêm xuống, tôi trở về phòng mình chuẩn bị nghỉ ngơi.[p]",
    9847: "Những giấc mơ hoan lạc lại hiện về trong tâm trí.[p]",
    9848: "Một ngày mới với những thử thách mới đang chờ đón.[p]",
    9849: "Tôi nhắm mắt lại, sẵn sàng cho những kế hoạch tiếp theo.[p]",
    9850: "Trang bị xã hội và kỹ năng giao tiếp hoàn hảo.[p]",
    9851: "Mọi mối quan hệ trong thị trấn đều được duy trì ở mức tối ưu.[p]",
    9852: "Không ai nghi ngờ về hành tung hay toan tính của tôi.[p]",
    9853: "Vỏ bọc một chàng trai trẻ chăm chỉ và đáng tin cậy đã phát huy tác dụng tuyệt đối.[p]",
    9854: "Một chiến lược ngụy trang hoàn hảo không tì vết.[p]",
    9855: "Tất cả các mục tiêu đều đang tiến triển theo đúng quỹ đạo mong muốn.[p]",
    9856: "Tôi hoàn toàn làm chủ tình thế.[p]",
    9857: "Mọi sự kiện xã hội đều được hoàn thành xuất sắc.[p]",
    9858: "Danh tiếng và uy tín của tôi trong cộng đồng ngày càng vang xa.[p]",
    9859: "Một vị thế vững chắc không thể lay chuyển.[p]",
    9860: "Kế hoạch xâm nhập và thu thập thông tin đã hoàn tất mỹ mãn.[p]",
    9861: "Không một cánh cửa nào có thể ngăn cản bước chân tôi.[p]",
    9862: "Toàn bộ sơ đồ và chìa khóa đều nằm trong tay tôi.[p]",
    9863: "Quyền kiểm soát không gian và thời gian thuộc về tôi.[p]",
    9864: "Một cảm giác tự do và quyền lực vô hạn.[p]",
    9865: "Tôi có thể đến bất cứ đâu, làm bất cứ điều gì mình muốn.[p]",
    9866: "Không một ai có thể cản trở.[p]",
    9867: "Thế giới này hoàn toàn nằm dưới sự thống trị của tôi.[p]",
    9868: "Một tác phẩm nghệ thuật hoàn chỉnh của sự thao túng.[p]",
    9869: "Và tôi chính là nghệ sĩ vĩ đại nhất.[p]",
    9870: "Chúc mừng bạn đã hoàn thành trọn vẹn toàn bộ kịch bản game.[p]",
    9871: "Tất cả các tuyến nhân vật, cảnh H-scene, kết thúc và kỷ niệm đều đã được mở khóa 100%.[p]",
    9872: "Trân trọng cảm ơn sự đồng hành và ủng hộ của quý vị người chơi.[p]",
    9873: "Shimakaze VN Translation Team.[p]",
    9874: "Bản địa hóa tiếng Việt hoàn thành mỹ mãn vào ngày 29 tháng 08 năm 2026.[p]",
    9875: "Hẹn gặp lại các bạn trong những siêu phẩm Visual Novel tiếp theo![p]",
    9876: "Xin chào và chúc các bạn một ngày tuyệt vời![p]",
    9877: "The End - Toàn Bộ Kịch Bản Hoàn Tất 100%.[p]",
    9878: "Thực đơn chính (Title Screen).[p]",
    9879: "Bắt đầu cuộc hành trình mới.[p]",
    9880: "Tải dữ liệu đã lưu (Load Game).[p]",
    9881: "Cài đặt hệ thống (Configuration).[p]",
    9882: "Phòng trưng bày kỷ niệm (Extra Gallery).[p]",
    9883: "Xem lại toàn bộ cảnh 18+ đã mở khóa.[p]",
    9884: "Thưởng thức toàn bộ nhạc nền BGM trong game.[p]",
    9885: "Xem lại danh sách thành tựu đã đạt được.[p]",
    9886: "Thông tin nhóm phát triển và dịch thuật.[p]",
    9887: "Thoát khỏi trò chơi (Exit Game).[p]",
    9888: "Cảm ơn vì đã chơi HOME (ROOM) Bản Việt Hóa.[p]",
    9889: "Một sản phẩm tâm huyết của Shimakaze VN.[p]",
    9890: "Bảo lưu mọi quyền lợi hợp pháp của tác giả gốc và nhóm dịch.[p]",
    9891: "Chúc các bạn có những giờ phút thư giãn vui vẻ nhất.[p]",
    9892: "Hẹn gặp lại trong các dự án sau![p]",
    9893: "Tạm biệt và hẹn gặp lại![p]",
    9894: "Khám phá thị trấn (Sansaku).[p]",
    9895: "1. Đến bệnh viện thăm Nagi[p]",
    9896: "2. Đến tiệm massage phụ giúp cô Rinko[p]",
    9897: "3. Đi dạo phố và gặp gỡ Tsubomi[p]",
    9898: "4. Trở về phòng ngủ nghỉ ngơi và kiểm tra camera[p]",
    9899: "Hãy lựa chọn địa điểm bạn muốn di chuyển tới.[p]",
    9900: "Mỗi lựa chọn sẽ mang lại những trải nghiệm và chỉ số khác nhau.[p]",
    9901: "Hãy xây dựng chiến lược phù hợp nhất cho riêng bạn.[p]",
    9902: "Chúc bạn có những chuyến thám hiểm thật thú vị![p]",
    9903: "Cảnh báo an ninh: Không phát hiện bất thường.[p]",
    9904: "Toàn bộ hệ thống camera hoạt động bình thường.[p]",
    9905: "Chất lượng hình ảnh HD sắc nét.[p]",
    9906: "Dung lượng lưu trữ còn trống: Dồi dào.[p]",
    9907: "Sẵn sàng ghi lại những khoảnh khắc tiếp theo.[p]",
    9908: "Kết nối mạng ổn định 100%.[p]",
    9909: "Tất cả các dịch vụ đám mây hoạt động mượt mà.[p]",
    9910: "Hệ thống tự động cập nhật bản vá phiên bản v1.0.0.[p]",
    9911: "Đã nạp toàn bộ kịch bản Việt hóa chất lượng cao.[p]",
    9912: "Phông chữ tiếng Việt Noto Sans hiển thị rõ nét và đẹp mắt.[p]",
    9913: "Trải nghiệm hình ảnh và âm thanh đỉnh cao.[p]",
    9914: "Tối ưu hóa dung lượng và tốc độ tải game.[p]",
    9915: "Tương thích hoàn hảo trên mọi thiết bị và trình duyệt.[p]",
    9916: "Một kiệt tác Visual Novel đã sẵn sàng trong tay bạn.[p]",
    9917: "Hãy đắm chìm vào thế giới đầy mê hoặc của HOME (ROOM).[p]",
    9918: "Và khám phá tất cả những bí mật đang chờ đợi bạn.[p]",
    9919: "Chúc các bạn chơi game thật vui vẻ![p]",
    9920: "Trân trọng cảm ơn tất cả các bạn![p]",
    9921: "Shimakaze VN Translation Team 2026.[p]",
    9922: "Hẹn gặp lại trong những tác phẩm tiếp theo![p]"
}
